"""Players: player info, search, the shared player profile and your progress."""

from typing import TYPE_CHECKING

from empire_core.enums import (
    AllianceRank,
    Kingdom,
    MapItemType,
    MercenaryMissionRarity,
    MercenaryMissionState,
    PremiumAccountType,
    TitleSystem,
)
from empire_core.utils.lazy import lazy_exports

from .models import (
    PERMANENT_BOOSTER_DURATION,
    AchievementProgress,
    AchievementsResponse,
    AllianceCityTitle,
    BoostedGlobalEffectsResponse,
    Booster,
    BoosterInfoResponse,
    DailyResetResponse,
    FactionPointsResponse,
    Festival,
    GetPlayerInfoRequest,
    GetPlayerInfoResponse,
    GloryPointsResponse,
    IslandTitle,
    LocationCapture,
    LootBoxAmount,
    LootBoxesResponse,
    LootBoxKeys,
    MercenaryMission,
    MercenaryMissionsResponse,
    MercenaryPackageRequest,
    MightPointsResponse,
    OfficerBonus,
    OfficerTraining,
    PlayerGift,
    PlayerGiftsResponse,
    PlayerOwnerInfo,
    PlayerProfileBase,
    RelocationInfoResponse,
    ResearchInfoResponse,
    SearchPlayerRequest,
    SearchPlayerResponse,
    SkipResearchRequest,
    SkipResearchResponse,
    StartResearchRequest,
    StartResearchResponse,
    TitleRanksResponse,
    TopTitleRanking,
)
from .service import PlayerDetailsBulkResult, PlayerService
from .titles import held_titles, player_title_ids, titles_in_order

if TYPE_CHECKING:
    from empire_core.gamedata import Achievement, Currency, Effect, GlobalEffect, LootBox, LootBoxType, Research, Title

__all__ = [
    "GetPlayerInfoRequest",
    "GetPlayerInfoResponse",
    "PlayerOwnerInfo",
    "LocationCapture",
    "SearchPlayerRequest",
    "SearchPlayerResponse",
    "PlayerProfileBase",
    "PERMANENT_BOOSTER_DURATION",
    "AchievementProgress",
    "AchievementsResponse",
    "AllianceCityTitle",
    "Booster",
    "BoosterInfoResponse",
    "FactionPointsResponse",
    "Festival",
    "GloryPointsResponse",
    "IslandTitle",
    "MightPointsResponse",
    "RelocationInfoResponse",
    "ResearchInfoResponse",
    "SkipResearchRequest",
    "SkipResearchResponse",
    "StartResearchRequest",
    "StartResearchResponse",
    "TitleRanksResponse",
    "TitleSystem",
    "PremiumAccountType",
    "TopTitleRanking",
    "PlayerDetailsBulkResult",
    "PlayerService",
    "held_titles",
    "player_title_ids",
    "titles_in_order",
    "BoostedGlobalEffectsResponse",
    "DailyResetResponse",
    "OfficerBonus",
    "OfficerTraining",
    "PlayerGift",
    "PlayerGiftsResponse",
    "LootBoxAmount",
    "LootBoxKeys",
    "LootBoxesResponse",
    "MercenaryMission",
    "MercenaryMissionsResponse",
    "MercenaryPackageRequest",
    "MercenaryMissionRarity",
    "MercenaryMissionState",
    "AllianceRank",
    "Kingdom",
    "MapItemType",
    "Achievement",
    "Currency",
    "Effect",
    "GlobalEffect",
    "LootBox",
    "LootBoxType",
    "Research",
    "Title",
]


if not TYPE_CHECKING:
    __getattr__ = lazy_exports(
        __name__,
        "empire_core.gamedata.ids",
        ("Achievement", "Currency", "Effect", "GlobalEffect", "LootBox", "LootBoxType", "Research", "Title"),
    )
