"""Commanders, castellans, generals, skills and equipment."""

from typing import TYPE_CHECKING

from empire_core.enums import EquipmentSlot, EquipmentType, Rareness, WearerType
from empire_core.utils.lazy import lazy_exports

from .models import (
    FACTION_BARON_ID,
    NO_GEM_ID,
    PICTURE_FACTION_CASTELLAN,
    PICTURE_ISLAND_CASTELLAN,
    PREMIUM_COMMANDER_ID,
    ActivatingSceatSkill,
    AddGeneralXpRequest,
    AlienEquipment,
    AssignGeneralRequest,
    AssignGeneralResponse,
    Castellan,
    Commander,
    CommanderEffect,
    CommanderEffects,
    CommanderRoster,
    EquipEquipmentRequest,
    Equipment,
    EquipmentBonus,
    GemInventoryResponse,
    GemStack,
    GetCommandersRequest,
    GetCommandersResponse,
    GetEquipmentInventoryRequest,
    GetEquipmentInventoryResponse,
    GetGeneralsRequest,
    GetGeneralsResponse,
    GetSkillsRequest,
    GetSkillsResponse,
    InventorySpace,
    LeaderBase,
    NewRelicsResponse,
    ObjectUpdateEvent,
    OwnedGeneral,
    RelicBonus,
    RelicGem,
    RelicInfo,
    RenameCommanderRequest,
    RenameCommanderResponse,
    ResetGeneralSkillsRequest,
    SelectedAbility,
    SetGeneralAbilitiesRequest,
    SkillList,
    UnlockGeneralSkillRequest,
)
from .service import CommandersService, EquipmentService, SkillsService

if TYPE_CHECKING:
    from empire_core.gamedata import Gem, GeneralAbility, GeneralSkill, LegendSkill, SceatSkill

__all__ = [
    "NO_GEM_ID",
    "EquipmentBonus",
    "RelicBonus",
    "RelicGem",
    "RelicInfo",
    "Equipment",
    "GetEquipmentInventoryRequest",
    "GetEquipmentInventoryResponse",
    "EquipEquipmentRequest",
    "PICTURE_FACTION_CASTELLAN",
    "PICTURE_ISLAND_CASTELLAN",
    "FACTION_BARON_ID",
    "PREMIUM_COMMANDER_ID",
    "AlienEquipment",
    "CommanderEffect",
    "CommanderEffects",
    "LeaderBase",
    "Commander",
    "Castellan",
    "GetCommandersRequest",
    "CommanderRoster",
    "GetCommandersResponse",
    "RenameCommanderRequest",
    "RenameCommanderResponse",
    "OwnedGeneral",
    "SelectedAbility",
    "GetGeneralsRequest",
    "GetGeneralsResponse",
    "AssignGeneralRequest",
    "AssignGeneralResponse",
    "SetGeneralAbilitiesRequest",
    "UnlockGeneralSkillRequest",
    "ResetGeneralSkillsRequest",
    "AddGeneralXpRequest",
    "GetSkillsRequest",
    "GetSkillsResponse",
    "SkillList",
    "ActivatingSceatSkill",
    "ObjectUpdateEvent",
    "EquipmentSlot",
    "WearerType",
    "EquipmentType",
    "Rareness",
    "CommandersService",
    "EquipmentService",
    "SkillsService",
    "NewRelicsResponse",
    "GemInventoryResponse",
    "GemStack",
    "InventorySpace",
    "Gem",
    "GeneralAbility",
    "GeneralSkill",
    "LegendSkill",
    "SceatSkill",
]


if not TYPE_CHECKING:
    __getattr__ = lazy_exports(
        __name__, "empire_core.gamedata.ids", ("Gem", "GeneralAbility", "GeneralSkill", "LegendSkill", "SceatSkill")
    )
