"""Combat maths ported from the game client."""

from .bonuses import (
    Bonus,
    CombatEffectType,
    EffectResolver,
    alliance_buff_bonuses,
    attacker_flank_effects,
    commander_bonuses,
    construction_item_bonuses,
    general_skill_bonuses,
    global_effect_bonuses,
    global_unit_attack_bonuses,
    legend_skill_value,
    parse_bonus_entries,
    parse_effect_spec,
    sceat_skill_bonuses,
)
from .capacity import (
    WaveCapacity,
    boost_to_modifier,
    flank_soldier_capacity,
    flank_tool_capacity,
    is_legendary_fight,
    max_attackers,
    max_wave_count,
    middle_soldier_capacity,
    middle_tool_capacity,
    yard_capacity,
)
from .defence import defender_flank_effects, event_camp_defence, npc_camp_defence
from .effects import AttackerFlankEffects, DefenderFlankEffects, Flank
from .solver import (
    FillOptions,
    Inventory,
    fill_flank_with_soldiers,
    fill_wave,
    fill_waves,
    pick_soldier_stack,
)
from .tools import ToolStrategy, check_flank, fill_flank_with_tools

__all__ = [
    "AttackerFlankEffects",
    "Bonus",
    "CombatEffectType",
    "EffectResolver",
    "DefenderFlankEffects",
    "FillOptions",
    "Flank",
    "Inventory",
    "WaveCapacity",
    "boost_to_modifier",
    "is_legendary_fight",
    "alliance_buff_bonuses",
    "attacker_flank_effects",
    "commander_bonuses",
    "construction_item_bonuses",
    "defender_flank_effects",
    "event_camp_defence",
    "general_skill_bonuses",
    "global_effect_bonuses",
    "global_unit_attack_bonuses",
    "legend_skill_value",
    "ToolStrategy",
    "check_flank",
    "fill_flank_with_soldiers",
    "fill_flank_with_tools",
    "fill_wave",
    "fill_waves",
    "flank_soldier_capacity",
    "flank_tool_capacity",
    "max_attackers",
    "max_wave_count",
    "middle_soldier_capacity",
    "middle_tool_capacity",
    "npc_camp_defence",
    "yard_capacity",
    "parse_bonus_entries",
    "parse_effect_spec",
    "sceat_skill_bonuses",
    "pick_soldier_stack",
]
