"""The army: units, production, the hospital and spy-report armies."""

from empire_core.enums import ProductionListId, SlotType, SpyArmySection

from .models import (
    BUY_UNIT_PACKAGE_SK,
    AddedUnit,
    AttackWave,
    CancelHealRequest,
    CancelHealResponse,
    CancelProductionRequest,
    CancelProductionResponse,
    CurrentProductionSlot,
    DismissManyWoundedRequest,
    DismissUnitsRequest,
    DismissUnitsResponse,
    DismissWoundedRequest,
    DismissWoundedResponse,
    DoubleProductionSlotRequest,
    DoubleProductionSlotResponse,
    GetProductionListRequest,
    GetProductionListResponse,
    GetUnitsRequest,
    GetUnitsResponse,
    HealAllRequest,
    HealAllResponse,
    HealUnitsRequest,
    HealUnitsResponse,
    HospitalSlot,
    ProduceUnitsRequest,
    ProduceUnitsResponse,
    ProductionList,
    ProductionSlot,
    SkipHealRequest,
    SkipHealResponse,
    UnitInventory,
    WaveFlank,
    WoundedUnits,
    wod_amount_pairs,
)
from .service import ArmyService
from .spy_army import SpyArmy, UnitStack

__all__ = [
    "AttackWave",
    "WaveFlank",
    "HealUnitsRequest",
    "HealUnitsResponse",
    "CancelHealRequest",
    "CancelHealResponse",
    "SkipHealRequest",
    "SkipHealResponse",
    "DismissWoundedRequest",
    "DismissManyWoundedRequest",
    "WoundedUnits",
    "DismissWoundedResponse",
    "HealAllRequest",
    "HealAllResponse",
    "ProductionList",
    "ProductionSlot",
    "CurrentProductionSlot",
    "HospitalSlot",
    "ProduceUnitsRequest",
    "ProduceUnitsResponse",
    "AddedUnit",
    "GetProductionListRequest",
    "GetProductionListResponse",
    "DoubleProductionSlotRequest",
    "DoubleProductionSlotResponse",
    "CancelProductionRequest",
    "CancelProductionResponse",
    "wod_amount_pairs",
    "BUY_UNIT_PACKAGE_SK",
    "UnitInventory",
    "GetUnitsRequest",
    "GetUnitsResponse",
    "DismissUnitsRequest",
    "DismissUnitsResponse",
    "ProductionListId",
    "SlotType",
    "ArmyService",
    "SpyArmy",
    "SpyArmySection",
    "UnitStack",
]
