"""
GGE Protocol Models - Pydantic models for Goodgame Empire protocol commands.

This package contains type-safe models for all GGE protocol commands.

Structure:
- base.py: Base classes and common types
- auth.py: Authentication commands (lli, lre, vpn, vln, etc.)
- chat.py: Alliance chat commands (acm, acl)
- alliance.py: Alliance commands (ahc, aha, ahr)
- castle.py: Castle commands (gcl, dcl, jca, arc, etc.)
- map.py: Map commands (gaa, fnm, adi, etc.)
- movement.py: Army movements (gam, and the abr/asr/mcm pushes)
- attack.py: Attack/spy commands (cra, csm, gas, etc.)
- building.py: Building commands (ebu, eup, emo, sbd, etc.)
- army.py: Army/soldier/hospital commands (bup, spl, gui, hru, etc.)
- defense.py: Defense commands (dfc, dfk, dfw, dfm)
- equipment.py: Equipment inventory commands (gei, eeq)

TODO (lower priority):
- shop.py: Shop/purchase commands (sbp, gbc)
- events.py: Event commands (sei, pep, hgh, sede)
- gifts.py: Gift commands (clb, gpg)
- quests.py: Quest commands (qsc, qdr, fcq)
- account.py: Account commands (gpi, scp, vpm, cpne, etc.)
- settings.py: Settings commands (ani, mvf, opt, hfl)
- misc.py: Miscellaneous commands (txi, txs, txc, gbl, etc.)
"""

from .alliance import (
    AllianceBookmark,
    AllianceBuilding,
    AllianceDiplomacyStatus,
    AllianceInfo,
    AllianceMember,
    AllianceMemberInfo,
    AllianceSearchResult,
    AllianceStorage,
    AskHelpRequest,
    AskHelpResponse,
    GetAllianceBookmarksRequest,
    GetAllianceBookmarksResponse,
    GetAllianceInfoRequest,
    GetAllianceInfoResponse,
    HelpAllRequest,
    HelpAllResponse,
    HelpMemberRequest,
    HelpMemberResponse,
    HelpRequestNotification,
    SearchAllianceRequest,
    SearchAllianceResponse,
)
from .army import (
    CancelHealRequest,
    CancelHealResponse,
    CancelProductionRequest,
    CancelProductionResponse,
    DeleteUnitsRequest,
    DeleteUnitsResponse,
    DeleteWoundedRequest,
    DeleteWoundedResponse,
    DoubleProductionRequest,
    DoubleProductionResponse,
    GetProductionQueueRequest,
    GetProductionQueueResponse,
    GetUnitsRequest,
    GetUnitsResponse,
    HealAllRequest,
    HealAllResponse,
    HealUnitsRequest,
    HealUnitsResponse,
    ProduceUnitsRequest,
    ProduceUnitsResponse,
    ProductionQueueItem,
    SendSupportRequest,
    SendSupportResponse,
    SkipHealRequest,
    SkipHealResponse,
    UnitInventory,
)
from .attack import (
    AttackInfoResponse,
    AttackPreset,
    AttackTargetArea,
    AttackType,
    AttackWave,
    CreateAttackRequest,
    CreateAttackResponse,
    CurrencyTotals,
    GetAttackInfoRequest,
    GetAttackInfoResponse,
    GetBossDungeonAttackInfoRequest,
    GetBossDungeonAttackInfoResponse,
    GetCapitalConquerInfoRequest,
    GetCapitalConquerInfoResponse,
    GetDungeonAttackInfoRequest,
    GetDungeonAttackInfoResponse,
    GetIslandAttackInfoRequest,
    GetIslandAttackInfoResponse,
    GetLandmarkAttackInfoRequest,
    GetLandmarkAttackInfoResponse,
    GetMetropolConquerInfoRequest,
    GetMetropolConquerInfoResponse,
    GetOutpostConquerInfoRequest,
    GetOutpostConquerInfoResponse,
    GetPresetsRequest,
    GetPresetsResponse,
    GetVillageAttackInfoRequest,
    GetVillageAttackInfoResponse,
    MinuteSkipDungeonRequest,
    MinuteSkipDungeonResponse,
    PresetArmy,
    SavePresetRequest,
    SavePresetResponse,
    SendSpyRequest,
    SendSpyResponse,
    SkipDungeonCooldownRequest,
    SkipDungeonCooldownResponse,
    SpyScreenInfoRequest,
    SpyScreenInfoResponse,
    WaveFlank,
)
from .auth import (
    CheckUsernameAvailableRequest,
    CheckUsernameAvailableResponse,
    CheckUsernameExistsRequest,
    CheckUsernameExistsResponse,
    LoginRequest,
    LoginResponse,
    PasswordRecoveryRequest,
    PasswordRecoveryResponse,
    PlayerData,
    RegisterRequest,
    RegisterResponse,
)
from .base import (
    DEFAULT_ZONE,
    BasePayload,
    BaseRequest,
    BaseResponse,
    GGECommand,
    HelpType,
    PlayerInfo,
    Position,
    ProductionListType,
    ResourceAmount,
    UnitCount,
    decode_chat_text,
    encode_chat_text,
    get_response_model,
    parse_response,
)
from .building import (
    BuildRequest,
    BuildResponse,
    BuyExtensionRequest,
    BuyExtensionResponse,
    CollectExtensionGiftRequest,
    CollectExtensionGiftResponse,
    DestroyBuildingRequest,
    DestroyBuildingResponse,
    FastCompleteRequest,
    FastCompleteResponse,
    MoveBuildingRequest,
    MoveBuildingResponse,
    RepairAllRequest,
    RepairAllResponse,
    RepairBuildingRequest,
    RepairBuildingResponse,
    SellBuildingRequest,
    SellBuildingResponse,
    TimeSkipBuildingRequest,
    TimeSkipBuildingResponse,
    UpgradeBuildingRequest,
    UpgradeBuildingResponse,
    UpgradeWallRequest,
    UpgradeWallResponse,
)
from .castle import (
    LOCATION_TYPES,
    CastleInfo,
    CastleProductionArea,
    DetailedCastleInfo,
    GetCastlesRequest,
    GetCastlesResponse,
    GetDetailedCastleRequest,
    GetDetailedCastleResponse,
    GetProductionRequest,
    GetProductionResponse,
    GetResourcesRequest,
    GetResourcesResponse,
    ProductionBonus,
    ProductionRates,
    RelocateCastleRequest,
    RelocateCastleResponse,
    RenameCastleRequest,
    RenameCastleResponse,
    ResourceProduction,
    SafeAmount,
    SelectCastleRequest,
    SelectCastleResponse,
    StorageCapacity,
    get_location_type_name,
)
from .chat import (
    AllianceChatLogRequest,
    AllianceChatLogResponse,
    AllianceChatMessageRequest,
    AllianceChatMessageResponse,
    ChatLogEntry,
    ChatMessageData,
)
from .commanders import (
    Castellan,
    Commander,
    CommanderEffect,
    CommanderRoster,
    Equipment,
    EquipmentBonus,
    EquipmentSlot,
    EquipmentType,
    GetCommandersRequest,
    GetCommandersResponse,
    RelicBonus,
    RenameCommanderRequest,
    RenameCommanderResponse,
    WearerType,
)
from .defense import (
    ChangeKeepDefenseRequest,
    ChangeMoatDefenseRequest,
    ChangeWallDefenseRequest,
    GetDefenseRequest,
    GetDefenseResponse,
    GetSupportDefenseRequest,
    GetSupportDefenseResponse,
    KeepDefense,
    MoatDefense,
    WallDefense,
    WallSection,
    WallSectionSetup,
)
from .equipment import (
    EquipEquipmentRequest,
    GetEquipmentInventoryRequest,
    GetEquipmentInventoryResponse,
)
from .inventory import SCEItem
from .map import (
    AllianceCrest,
    AllianceEmblem,
    FindNPCRequest,
    FindNPCResponse,
    GetMapAreaRequest,
    GetMapAreaResponse,
    Kingdom,
    MapAreaItem,
    MapItemType,
    MapObject,
    NPCLocation,
)
from .messages import (
    BattleSpyDataRequest,
    BattleSpyDataResponse,
    MessageInfo,
    SystemNotificationEvent,
)
from .movement import (
    GetMovementsRequest,
    GetMovementsResponse,
    MovementArea,
    MovementArmy,
    MovementMarket,
    MovementOwner,
    MovementRecord,
    MovementSpy,
    MovementUnitInfo,
    MovementWrapper,
    OwnerCastlePosition,
    OwnerCrest,
    OwnerFaction,
)
from .player import (
    GetPlayerInfoRequest,
    GetPlayerInfoResponse,
    LocationCapture,
    PlayerOwnerInfo,
    SearchPlayerRequest,
    SearchPlayerResponse,
)
from .ranking import (
    GetHighscoreRequest,
    GetHighscoreResponse,
    GetRankingListRequest,
    GetRankingListResponse,
    LeaderboardScore,
    RankingCategory,
    RankingEntry,
    RankingType,
)
from .skills import (
    ActivatingSceatSkill,
    AddGeneralXpRequest,
    AssignGeneralRequest,
    AssignGeneralResponse,
    General,
    GetGeneralsRequest,
    GetGeneralsResponse,
    GetSkillsRequest,
    GetSkillsResponse,
    ObjectUpdateEvent,
    ResetGeneralSkillsRequest,
    SelectedAbility,
    SetGeneralAbilitiesRequest,
    SkillList,
    UnlockGeneralSkillRequest,
)

__all__ = [
    # Base
    "GGECommand",
    "DEFAULT_ZONE",
    "HelpType",
    "ProductionListType",
    "BasePayload",
    "BaseRequest",
    "BaseResponse",
    "Position",
    "ResourceAmount",
    "UnitCount",
    "PlayerInfo",
    "encode_chat_text",
    "decode_chat_text",
    "get_response_model",
    "parse_response",
    # Auth
    "LoginRequest",
    "LoginResponse",
    "PlayerData",
    "RegisterRequest",
    "RegisterResponse",
    "CheckUsernameAvailableRequest",
    "CheckUsernameAvailableResponse",
    "CheckUsernameExistsRequest",
    "CheckUsernameExistsResponse",
    "PasswordRecoveryRequest",
    "PasswordRecoveryResponse",
    # Chat
    "AllianceChatMessageRequest",
    "AllianceChatMessageResponse",
    "ChatMessageData",
    "AllianceChatLogRequest",
    "AllianceChatLogResponse",
    "ChatLogEntry",
    # Alliance
    "AllianceMember",
    "AllianceInfo",
    "AllianceBuilding",
    "AllianceStorage",
    "AllianceMemberInfo",
    "AllianceDiplomacyStatus",
    "AllianceBookmark",
    "GetAllianceBookmarksRequest",
    "GetAllianceBookmarksResponse",
    "GetAllianceInfoRequest",
    "GetAllianceInfoResponse",
    "HelpMemberRequest",
    "HelpMemberResponse",
    "HelpAllRequest",
    "HelpAllResponse",
    "AskHelpRequest",
    "AskHelpResponse",
    "HelpRequestNotification",
    "SearchAllianceRequest",
    "SearchAllianceResponse",
    "AllianceSearchResult",
    # Castle
    "GetCastlesRequest",
    "GetCastlesResponse",
    "CastleInfo",
    "GetDetailedCastleRequest",
    "GetDetailedCastleResponse",
    "DetailedCastleInfo",
    "CastleProductionArea",
    "ResourceProduction",
    "StorageCapacity",
    "ProductionBonus",
    "SafeAmount",
    "SelectCastleRequest",
    "SelectCastleResponse",
    "RenameCastleRequest",
    "RenameCastleResponse",
    "RelocateCastleRequest",
    "RelocateCastleResponse",
    "GetResourcesRequest",
    "GetResourcesResponse",
    "GetProductionRequest",
    "GetProductionResponse",
    "ProductionRates",
    # Map
    "Kingdom",
    "MapItemType",
    "MapAreaItem",
    "GetMapAreaRequest",
    "GetMapAreaResponse",
    "MapObject",
    "AllianceCrest",
    "AllianceEmblem",
    "GetMovementsRequest",
    "GetMovementsResponse",
    "MovementArea",
    "MovementArmy",
    "MovementMarket",
    "MovementOwner",
    "MovementRecord",
    "MovementSpy",
    "MovementUnitInfo",
    "MovementWrapper",
    "OwnerCastlePosition",
    "OwnerCrest",
    "OwnerFaction",
    "FindNPCRequest",
    "FindNPCResponse",
    "NPCLocation",
    # Player
    "GetPlayerInfoRequest",
    "GetPlayerInfoResponse",
    "PlayerOwnerInfo",
    "LocationCapture",
    "LOCATION_TYPES",
    "get_location_type_name",
    "SearchPlayerRequest",
    "SearchPlayerResponse",
    # Attack
    "AttackType",
    "AttackWave",
    "GetAttackInfoRequest",
    "GetAttackInfoResponse",
    "AttackTargetArea",
    "WaveFlank",
    "AttackInfoResponse",
    "GetBossDungeonAttackInfoRequest",
    "GetBossDungeonAttackInfoResponse",
    "GetCapitalConquerInfoRequest",
    "GetCapitalConquerInfoResponse",
    "GetDungeonAttackInfoRequest",
    "GetDungeonAttackInfoResponse",
    "GetIslandAttackInfoRequest",
    "GetIslandAttackInfoResponse",
    "GetLandmarkAttackInfoRequest",
    "GetLandmarkAttackInfoResponse",
    "GetMetropolConquerInfoRequest",
    "GetMetropolConquerInfoResponse",
    "GetOutpostConquerInfoRequest",
    "GetOutpostConquerInfoResponse",
    "GetVillageAttackInfoRequest",
    "GetVillageAttackInfoResponse",
    "CreateAttackRequest",
    "CreateAttackResponse",
    "CurrencyTotals",
    "SendSpyRequest",
    "SendSpyResponse",
    "SpyScreenInfoRequest",
    "SpyScreenInfoResponse",
    "GetPresetsRequest",
    "GetPresetsResponse",
    "AttackPreset",
    "PresetArmy",
    "SavePresetRequest",
    "SavePresetResponse",
    "MinuteSkipDungeonRequest",
    "MinuteSkipDungeonResponse",
    "SkipDungeonCooldownRequest",
    "SkipDungeonCooldownResponse",
    # Messages
    "MessageInfo",
    "SystemNotificationEvent",
    "BattleSpyDataRequest",
    "BattleSpyDataResponse",
    # Defense
    "GetDefenseRequest",
    "GetDefenseResponse",
    "WallSection",
    "WallSectionSetup",
    "WallDefense",
    "KeepDefense",
    "MoatDefense",
    "ChangeKeepDefenseRequest",
    "ChangeWallDefenseRequest",
    "ChangeMoatDefenseRequest",
    "GetSupportDefenseRequest",
    "GetSupportDefenseResponse",
    # Building
    "BuildRequest",
    "BuildResponse",
    "UpgradeBuildingRequest",
    "UpgradeBuildingResponse",
    "MoveBuildingRequest",
    "MoveBuildingResponse",
    "SellBuildingRequest",
    "SellBuildingResponse",
    "DestroyBuildingRequest",
    "DestroyBuildingResponse",
    "FastCompleteRequest",
    "FastCompleteResponse",
    "TimeSkipBuildingRequest",
    "TimeSkipBuildingResponse",
    "UpgradeWallRequest",
    "UpgradeWallResponse",
    "RepairBuildingRequest",
    "RepairBuildingResponse",
    "RepairAllRequest",
    "RepairAllResponse",
    "BuyExtensionRequest",
    "BuyExtensionResponse",
    "CollectExtensionGiftRequest",
    "CollectExtensionGiftResponse",
    # Army
    "ProduceUnitsRequest",
    "ProduceUnitsResponse",
    "GetProductionQueueRequest",
    "GetProductionQueueResponse",
    "ProductionQueueItem",
    "DoubleProductionRequest",
    "DoubleProductionResponse",
    "CancelProductionRequest",
    "CancelProductionResponse",
    "GetUnitsRequest",
    "GetUnitsResponse",
    "UnitInventory",
    "DeleteUnitsRequest",
    "DeleteUnitsResponse",
    "HealUnitsRequest",
    "HealUnitsResponse",
    "CancelHealRequest",
    "CancelHealResponse",
    "SkipHealRequest",
    "SkipHealResponse",
    "DeleteWoundedRequest",
    "DeleteWoundedResponse",
    "HealAllRequest",
    "HealAllResponse",
    "SendSupportRequest",
    "SendSupportResponse",
    "General",
    "SelectedAbility",
    "GetCommandersRequest",
    "GetEquipmentInventoryRequest",
    "GetEquipmentInventoryResponse",
    "EquipEquipmentRequest",
    "GetGeneralsRequest",
    "GetGeneralsResponse",
    "AssignGeneralRequest",
    "AssignGeneralResponse",
    "SetGeneralAbilitiesRequest",
    "UnlockGeneralSkillRequest",
    "ResetGeneralSkillsRequest",
    "AddGeneralXpRequest",
    "GetSkillsRequest",
    "GetSkillsResponse",
    "SkillList",
    "ActivatingSceatSkill",
    "ObjectUpdateEvent",
    "GetCommandersResponse",
    "CommanderRoster",
    "RenameCommanderRequest",
    "RenameCommanderResponse",
    "Castellan",
    "Commander",
    "CommanderEffect",
    "Equipment",
    "EquipmentBonus",
    "EquipmentSlot",
    "EquipmentType",
    "RelicBonus",
    "WearerType",
    "SCEItem",
    # Ranking
    "RankingType",
    "RankingCategory",
    "RankingEntry",
    "GetHighscoreRequest",
    "GetHighscoreResponse",
    "GetRankingListRequest",
    "GetRankingListResponse",
    "LeaderboardScore",
]
