"""The generated game-data id enums and the script that writes them."""

import importlib.util
import json
import logging
import os
import shutil
import subprocess
import sys
from enum import Enum
from pathlib import Path
from typing import Any

import pytest

from empire_core import gamedata
from empire_core.gamedata import GameData, default_cache_dir, ids
from empire_core.gamedata.data import CACHE_FILENAME_TEMPLATE
from tests.test_gamedata import LOOKUP_PAYLOAD, PAYLOAD

ROOT = Path(__file__).resolve().parents[1]
IDS_DIR = ROOT / "src" / "empire_core" / "gamedata" / "ids"


def _load_script():
    spec = importlib.util.spec_from_file_location(
        "generate_gamedata_ids", ROOT / "scripts" / "generate_gamedata_ids.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


gen = _load_script()

ENUMS = [getattr(ids, name) for name in ids.__all__ if isinstance(getattr(ids, name), type)]

# Which GameData table each enum's values index.
TABLE_OF = {
    "Unit": "units",
    "Tool": "tools",
    "Effect": "effects",
    "EffectType": "effect_types",
    "CurrencyId": "currencies",
    "General": "generals",
    "GeneralAbility": "general_abilities",
    "GeneralSkill": "general_skills",
    "LegendSkill": "legend_skills",
    "RaidBoss": "raid_bosses",
    "GlobalEffect": "global_effects",
}


def _cached_game_data() -> GameData | None:
    cache = default_cache_dir() / CACHE_FILENAME_TEMPLATE.format(version=ids.ITEMS_VERSION)
    return GameData._read_cache(cache, ids.ITEMS_VERSION)


class TestPackage:
    def test_every_enum_is_exported_from_gamedata(self):
        assert {e.__name__ for e in ENUMS} == set(TABLE_OF) | {"Currency"}
        for enum in ENUMS:
            assert getattr(gamedata, enum.__name__) is enum
        assert gamedata.ITEMS_VERSION == ids.ITEMS_VERSION

    def test_no_member_is_an_alias(self):
        for enum in ENUMS:
            assert len(list(enum)) == len(enum.__members__), enum.__name__

    def test_every_file_names_the_version_it_came_from(self):
        header = f"# Generated by scripts/generate_gamedata_ids.py from items {ids.ITEMS_VERSION}; do not edit.\n"
        files = sorted(IDS_DIR.glob("*.py"))
        assert files
        for path in files:
            assert path.read_text().startswith(header), path.name

    def test_known_ids(self):
        assert ids.Currency.GXP1 == "GXP1"
        assert ids.General.TORIL == 101
        assert ids.Unit.MEAD_RANGER_L6 == 211
        assert (ids.GlobalEffect.SPEED_BOOST_2, ids.GlobalEffect.SPEED_BOOST_11) == (2, 11)
        assert ids.CurrencyId[ids.Currency.KT.name] == 1

    def test_the_suite_fixtures_name_the_same_ids(self):
        payload: dict[str, Any] = dict(LOOKUP_PAYLOAD)
        payload["units"] = [*payload["units"], *PAYLOAD["units"]]
        data = GameData.parse(ids.ITEMS_VERSION, payload)
        checked = 0
        for table in gen.tables(data):
            enum = getattr(ids, table.enum)
            for name, value in gen.members(table):
                if name in enum.__members__:
                    assert enum[name].value == value, f"{table.enum}.{name}"
                    checked += 1
        assert checked >= 10

    def test_every_value_is_in_the_items_data(self):
        data = _cached_game_data()
        if data is None:
            pytest.skip(f"no cached items v{ids.ITEMS_VERSION}")
            return
        for enum in ENUMS:
            if enum is ids.Currency:
                keys = {row.json_key for row in data.currencies.values()}
                assert {m.value for m in enum} <= keys
                continue
            table = getattr(data, TABLE_OF[enum.__name__])
            assert {m.value for m in enum} == set(table), enum.__name__

    def test_regenerating_from_the_same_items_changes_nothing(self):
        # The full items file is ~20 MB and not in the repo; point EMPIRE_CORE_ITEMS_JSON at it.
        path = os.environ.get("EMPIRE_CORE_ITEMS_JSON")
        if not path:
            pytest.skip("EMPIRE_CORE_ITEMS_JSON is not set")
            return
        payload = json.loads(Path(path).read_text())
        data = GameData.parse(gen.items_version(Path(path), payload), payload)
        if data.version != ids.ITEMS_VERSION:
            pytest.skip(f"{path} is items v{data.version}, not v{ids.ITEMS_VERSION}")
        committed = {file.name: file.read_text() for file in IDS_DIR.glob("*.py")}
        assert gen.render(data) == committed


class TestGenerator:
    @pytest.fixture
    def data(self) -> GameData:
        return GameData.parse("786.03", LOOKUP_PAYLOAD)

    def members(self, data: GameData, enum: str) -> dict[str, object]:
        table = next(t for t in gen.tables(data) if t.enum == enum)
        return dict(gen.members(table))

    @pytest.mark.parametrize(
        "text, expected",
        [
            ("MeadRanger", "MEAD_RANGER"),
            ("CooldownReductionRBC", "COOLDOWN_REDUCTION_RBC"),
            ("relicOffensiveMeleeBonusPVP", "RELIC_OFFENSIVE_MELEE_BONUS_PVP"),
            ("DecoCatalyst1", "DECO_CATALYST1"),
        ],
    )
    def test_camel_case_becomes_upper_snake(self, text, expected):
        assert gen.to_snake(text) == expected

    def test_identifiers_are_valid_and_public(self):
        assert gen.identifier("3rd place!", "U") == "U_3RD_PLACE"
        assert gen.identifier("", "U") == "U"
        assert gen.identifier("a-b  c", "U") == "A_B_C"
        assert gen.identifier("None", "U") == "NONE"

    def test_units_carry_their_level_and_colliding_ones_their_id(self, data):
        assert self.members(data, "Unit") == {
            "OGERMACE_7": 7,
            "OGERMACE_68": 68,
            "MEAD_RANGER_L6": 211,
            "MEAD_RANGER_L7": 212,
        }
        assert self.members(data, "Tool") == {
            "ELITE_COMBO_RAM_113": 113,
            "ELITE_COMBO_RAM_564": 564,
            "PREMIUMSTAKES_L2": 646,
        }

    def test_every_member_of_a_colliding_group_is_suffixed(self, data):
        assert self.members(data, "GlobalEffect") == {
            "COOLDOWN_REDUCTION_RBC": 1,
            "SPEED_BOOST_2": 2,
            "SPEED_BOOST_11": 11,
        }

    def test_skills_name_their_general_and_level(self, data):
        assert self.members(data, "GeneralSkill") == {
            "TORIL_ASPECTOFTHE_DRAGON_L1": 10110201,
            "TORIL_ASPECTOFTHE_DRAGON_L2": 10110202,
            "G102_ASPECTOFTHE_DRAGON_L1": 10210201,
        }
        assert self.members(data, "GeneralAbility") == {"POWER_SURGE_L1": 10011, "POWER_SURGE_L2": 10012}
        assert self.members(data, "LegendSkill") == {"GATE_REDUCTION_T0_G1_L1": 1, "GATE_REDUCTION_T0_G1_L2": 2}

    def test_currencies_by_key_and_by_id_share_names(self, data):
        assert self.members(data, "Currency") == {"KT": "KT", "DD": "DD"}
        assert self.members(data, "CurrencyId") == {"KT": 1, "DD": 100000}

    def test_output_is_deterministic_and_importable(self, data, tmp_path, monkeypatch):
        first = gen.render(data)
        tables: dict[str, Any] = LOOKUP_PAYLOAD
        reversed_payload = {key: list(reversed(rows)) for key, rows in tables.items()}
        assert gen.render(GameData.parse("786.03", reversed_payload)) == first

        package = tmp_path / "fake_ids"
        gen.write(first, package)
        spec = importlib.util.spec_from_file_location(
            "fake_ids", package / "__init__.py", submodule_search_locations=[str(package)]
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        monkeypatch.setitem(sys.modules, "fake_ids", module)
        spec.loader.exec_module(module)
        assert module.GlobalEffect.SPEED_BOOST_11 == 11
        assert issubclass(module.Currency, str) and issubclass(module.Currency, Enum)
        assert module.ITEMS_VERSION == "786.03"

    def test_output_is_ruff_clean(self, data, tmp_path):
        ruff = shutil.which("ruff")
        if ruff is None:
            pytest.skip("ruff is not installed")
            return
        gen.write(gen.render(data), tmp_path)
        subprocess.run([ruff, "format", "--check", "--config", str(ROOT / "pyproject.toml"), str(tmp_path)], check=True)
        subprocess.run([ruff, "check", "--config", str(ROOT / "pyproject.toml"), str(tmp_path)], check=True)

    def test_items_version_comes_from_the_file(self, tmp_path):
        payload = {"versionInfo": {"version": {"@value": "786.03"}}}
        assert gen.items_version(tmp_path / "whatever.json", payload) == "786.03"
        assert gen.items_version(tmp_path / "items_v785.01.json", {}) == "785.01"
        with pytest.raises(SystemExit):
            gen.items_version(tmp_path / "items.json", {})


class TestStaleness:
    def test_is_current(self):
        assert ids.is_current(GameData(version=ids.ITEMS_VERSION))
        assert not ids.is_current(GameData(version="0.01"))

    @pytest.fixture
    def load(self, monkeypatch, tmp_path):
        monkeypatch.setattr("empire_core.gamedata.data._warned_versions", set())
        monkeypatch.setattr("empire_core.gamedata.data.fetch_items_data", lambda version: PAYLOAD)

        def load(version: str) -> GameData:
            monkeypatch.setattr("empire_core.gamedata.data.get_items_version", lambda: version)
            return GameData.load(cache_dir=tmp_path)

        return load

    def stale_warnings(self, caplog) -> list[str]:
        return [r.getMessage() for r in caplog.records if "scripts/generate_gamedata_ids.py" in r.getMessage()]

    def test_load_warns_once_when_the_ids_are_from_another_version(self, load, caplog):
        with caplog.at_level(logging.WARNING, logger="empire_core.gamedata.data"):
            load("0.01")
            load("0.01")

        (message,) = self.stale_warnings(caplog)
        assert "v0.01" in message and f"v{ids.ITEMS_VERSION}" in message

    def test_load_is_quiet_for_the_version_the_ids_came_from(self, load, caplog):
        with caplog.at_level(logging.WARNING, logger="empire_core.gamedata.data"):
            load(ids.ITEMS_VERSION)

        assert self.stale_warnings(caplog) == []
