"""The generated game-data id enums and the script that writes them."""

import copy
import importlib.util
import json
import logging
import os
import pickle
import shutil
import subprocess
import sys
from enum import Enum
from pathlib import Path
from typing import Any

import pytest
from pydantic import BaseModel

from empire_core import gamedata
from empire_core.gamedata import GameData, UnitStats, default_cache_dir, ids
from empire_core.gamedata.data import CACHE_FILENAME_TEMPLATE, ROW_TABLES, rows_by_id
from empire_core.protocol.models.skills import SetGeneralAbilitiesRequest
from empire_core.utils.enums import Kingdom
from tests.test_gamedata import LOOKUP_PAYLOAD, PAYLOAD

ROOT = Path(__file__).resolve().parents[1]
IDS_DIR = ROOT / "src" / "empire_core" / "gamedata" / "ids"


def _load_script():
    spec = importlib.util.spec_from_file_location(
        "generate_gamedata_ids", ROOT / "scripts" / "generate_gamedata_ids.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


gen = _load_script()

ENUMS = [getattr(ids, name) for name in ids.__all__ if isinstance(getattr(ids, name), type)]

# Rows of the tables GameData does not model, as the items payload has them, from v786.03.
IDS_PAYLOAD: dict[str, Any] = {
    **LOOKUP_PAYLOAD,
    "effects": [{"effectID": "1", "name": "fameDefenseBonus", "effectTypeID": "0", "capID": "0", "sortOrder": "6.9.1"}],
    "buildings": [
        {"wodID": 171, "name": "Keep", "level": "1", "group": "Building", "type": "Level1"},
        {"wodID": 172, "name": "Keep", "level": "2", "group": "Building", "type": "Level2"},
        {"wodID": 301, "comment2": "Supplies1", "group": "Building", "type": "Supplies1", "name": "Deco", "level": "1"},
        {"wodID": 401, "name": "Guard", "level": "0", "group": "Tower", "type": "Placeholder"},
        {"wodID": 501, "name": "Castlewall", "level": "1", "group": "Defence", "type": "Level1", "wallBonus": "30"},
    ],
    "researches": [
        {"researchID": "1", "comment2": "Rekrutierungsgeschw", "groupID": "1", "level": "1"},
        {"researchID": "256", "comment2": "recruitment speed", "groupID": "41", "level": "1"},
    ],
    "events": [
        {"eventID": "5", "comment2": "Herald of the Invasion", "eventType": "NomadInvasion"},
        {"eventID": "6", "comment2": "Prime Day Special Offer", "eventType": "Paymentreward"},
        {"eventID": "74", "eventType": "Paymentreward"},
    ],
    "lootBoxes": [{"lootBoxID": "1", "name": "MysteryBoxBronze", "rarity": "1"}],
    "equipment_groups": [{"itemGroupID": "102", "name": "AttackPVP", "wearerID": "2", "slotID": "6"}],
    "eventAutoScalingDifficultyTypes": [{"difficultyTypeID": "2", "name": "easyPlus"}],
    "constructionItems": [
        {
            "constructionItemID": "1",
            "name": "barracksCost",
            "constructionItemGroupID": "1",
            "level": "1",
            "rarenessID": "1",
        },
    ],
}

# Which GameData table each enum's values index.
TABLE_OF: dict[str, str] = {
    "Building": "buildings",
    "ConstructionItem": "construction_items",
    "DifficultyType": "difficulty_types",
    "EquipmentGroup": "equipment_groups",
    "Event": "events",
    "LootBox": "loot_boxes",
    "Research": "researches",
    "Unit": "units",
    "Tool": "tools",
    "Effect": "effects",
    "EffectType": "effect_types",
    "CurrencyId": "currencies",
    "General": "generals",
    "GeneralAbility": "general_abilities",
    "GeneralSkill": "general_skills",
    "LegendSkill": "legend_skills",
    "RaidBoss": "raid_bosses",
    "GlobalEffect": "global_effects",
}


def _cached_game_data() -> GameData | None:
    cache = default_cache_dir() / CACHE_FILENAME_TEMPLATE.format(version=ids.ITEMS_VERSION)
    return GameData._read_cache(cache, ids.ITEMS_VERSION)


class TestPackage:
    def test_every_enum_is_exported_from_gamedata(self):
        assert {e.__name__ for e in ENUMS} == set(TABLE_OF) | {"Currency"}
        for enum in ENUMS:
            assert getattr(gamedata, enum.__name__) is enum
        assert gamedata.ITEMS_VERSION == ids.ITEMS_VERSION

    def test_no_member_is_an_alias(self):
        for enum in ENUMS:
            assert len(list(enum)) == len(enum.__members__), enum.__name__

    def test_every_file_names_the_version_it_came_from(self):
        header = f"# Generated by scripts/generate_gamedata_ids.py from items {ids.ITEMS_VERSION}; do not edit.\n"
        files = sorted(IDS_DIR.glob("*.py"))
        assert files
        for path in files:
            assert path.read_text().startswith(header), path.name

    def test_known_ids(self):
        assert ids.Currency.GXP1 == "GXP1"
        assert ids.General.TORIL == 101
        assert ids.Unit.MEAD_RANGER_L6 == 211
        assert (ids.GlobalEffect.SPEED_BOOST_2, ids.GlobalEffect.SPEED_BOOST_11) == (2, 11)
        assert ids.CurrencyId[ids.Currency.KT.name] == 1

    def test_the_suite_fixtures_name_the_same_ids(self):
        payload = dict(IDS_PAYLOAD)
        payload["units"] = [*payload["units"], *PAYLOAD["units"]]
        data = GameData.parse(ids.ITEMS_VERSION, payload)
        checked = 0
        for table in gen.tables(data):
            enum = getattr(ids, table.enum)
            for name, value in gen.members(table):
                if name in enum.__members__:
                    assert enum[name].value == value, f"{table.enum}.{name}"
                    checked += 1
        assert checked >= 20

    def test_every_value_is_in_the_items_data(self):
        data = _cached_game_data()
        if data is None:
            pytest.skip(f"no cached items v{ids.ITEMS_VERSION}")
            return
        for enum in ENUMS:
            if enum is ids.Currency:
                keys = {row.json_key for row in data.currencies.values()}
                assert {m.value for m in enum} <= keys
                continue
            table = getattr(data, TABLE_OF[enum.__name__])
            assert {m.value for m in enum} == set(table), enum.__name__

    def test_regenerating_from_the_same_items_changes_nothing(self):
        # The full items file is ~20 MB and not in the repo; point EMPIRE_CORE_ITEMS_JSON at it.
        path = os.environ.get("EMPIRE_CORE_ITEMS_JSON")
        if not path:
            pytest.skip("EMPIRE_CORE_ITEMS_JSON is not set")
            return
        payload = json.loads(Path(path).read_text())
        data = GameData.parse(gen.items_version(Path(path), payload), payload)
        if data.version != ids.ITEMS_VERSION:
            pytest.skip(f"{path} is items v{data.version}, not v{ids.ITEMS_VERSION}")
        committed = {file.name: file.read_text() for file in IDS_DIR.glob("*.py")}
        assert gen.render(data) == committed


@pytest.fixture
def lookup_data() -> GameData:
    return GameData.parse(ids.ITEMS_VERSION, IDS_PAYLOAD)


class TestMemberData:
    def test_fixed_columns_the_name_does_not_say_are_baked_in(self):
        unit = ids.Unit.VETERAN_SABERSLASHER
        assert (unit.value, unit.level, unit.role) == (5, -1, "melee")
        assert (ids.Unit.MEAD_RANGER_L6.level, ids.Unit.MEAD_RANGER_L6.role) == (6, "ranged")
        assert ids.General.TORIL.rarity_id == 4
        assert ids.GeneralSkill.TORIL_ASPECTOFTHE_DRAGON_L1.general_id == ids.General.TORIL
        assert ids.Currency.KT.currency_id == ids.CurrencyId.KT
        assert ids.CurrencyId.KT.json_key == ids.Currency.KT
        assert (ids.Building.KEEP_L1.value, ids.Building.KEEP_L1.group, ids.Building.KEEP_L1.level) == (
            171,
            "Building",
            1,
        )
        assert (ids.Research.RECRUITMENT_SPEED_G41_L1.group_id, ids.Research.RECRUITMENT_SPEED_G41_L1.level) == (41, 1)
        assert ids.ConstructionItem.BARRACKS_COST_G1_L1.rareness_id == 1
        assert (ids.EquipmentGroup.ATTACK_PVP.wearer_id, ids.EquipmentGroup.ATTACK_PVP.slot_id) == (2, 6)
        assert ids.LootBox.MYSTERY_BOX_BRONZE_R1.rarity == 1
        assert any(tool.category == "Defence" for tool in ids.Tool)

    def test_columns_the_name_says_are_not_baked_in(self):
        for member, dropped in [
            (ids.Unit.MEAD_RANGER_L6, "unit_type"),
            (ids.Tool.PREMIUMSTAKES, "tool_type"),
            (ids.General.TORIL, "row_name"),
            (ids.Building.KEEP_L1, "building_type"),
            (ids.LegendSkill.GATE_REDUCTION_T0_G1_L1, "effect_type"),
        ]:
            assert not hasattr(member, dropped), (member, dropped)

    @pytest.mark.parametrize(
        "enum", ["EffectType", "RaidBoss", "GlobalEffect", "Event", "DifficultyType"], ids=lambda name: name
    )
    def test_an_enum_without_columns_is_plain(self, enum):
        text = Path(str(sys.modules[getattr(ids, enum).__module__].__file__)).read_text()
        assert "__new__" not in text and "from __future__" not in text
        assert f"class {enum}(IntEnum):" in text

    def test_baked_columns_match_the_generated_rows(self):
        payload = dict(IDS_PAYLOAD)
        payload["units"] = [*payload["units"], *PAYLOAD["units"]]
        data = GameData.parse(ids.ITEMS_VERSION, payload)
        for table in gen.tables(data):
            enum = getattr(ids, table.enum)
            for row in table.rows:
                member = enum._value2member_map_.get(row.value)
                if member is not None:
                    assert tuple(getattr(member, a.name) for a in table.attrs) == row.attrs, member

    def test_members_are_their_values(self):
        unit, currency, event = ids.Unit.MEAD_RANGER_L6, ids.Currency.KT, ids.Event.NOMAD_INVASION
        assert unit == 211 and hash(unit) == hash(211) and {211: "x"}[unit] == "x"
        assert event == 5 and isinstance(event, int)
        assert currency == "KT" and hash(currency) == hash("KT")
        for member in (unit, currency, event):
            assert pickle.loads(pickle.dumps(member)) is member
            assert copy.copy(member) is member and copy.deepcopy(member) is member
        assert json.dumps([unit, currency, event]) == '[211, "KT", 5]'
        assert ids.Unit(211) is unit and ids.Currency("KT") is currency and ids.Event(5) is event

    def test_members_go_on_the_wire_as_plain_values(self):
        request = SetGeneralAbilitiesRequest(GID=ids.General.TORIL, SAIDS=[[0, ids.GeneralAbility.POWER_SURGE_L1]])
        payload = request.to_payload()
        assert payload == {"GID": 101, "SAIDS": [[0, 10011]]}
        assert type(payload["GID"]) is int and type(payload["SAIDS"][0][1]) is int

        class Typed(BaseModel):
            unit: ids.Unit
            currency: ids.Currency
            event: ids.Event

        typed = Typed.model_validate({"unit": 211, "currency": "KT", "event": 5})
        assert typed.unit is ids.Unit.MEAD_RANGER_L6 and typed.event is ids.Event.NOMAD_INVASION
        assert typed.model_dump(mode="json") == {"unit": 211, "currency": "KT", "event": 5}

    def test_game_data_lookups_take_members(self, lookup_data):
        assert lookup_data.get_unit(ids.Unit.MEAD_RANGER_L6) is lookup_data.units[211]
        assert lookup_data.currency(ids.Currency.KT) is lookup_data.currencies[1]
        assert lookup_data.generals.get(ids.General.TORIL) is lookup_data.generals[101]

    def test_the_enums_load_lazily(self):
        code = (
            "import sys, empire_core, empire_core.gamedata as g\n"
            "assert 'empire_core.gamedata.ids' not in sys.modules\n"
            "g.Unit\n"
            "assert 'empire_core.gamedata.ids' in sys.modules\n"
        )
        subprocess.run([sys.executable, "-c", code], check=True)


class TestRecords:
    def test_a_modeled_table_gives_its_model(self, lookup_data):
        d = lookup_data
        assert d.record(ids.Unit.MEAD_RANGER_L6) is d.units[211]
        assert d.record(ids.Tool.ELITE_COMBO_RAM_113) is d.tools[113]
        assert d.record(ids.Effect.FAME_DEFENSE_BONUS) is d.effects[1]
        assert d.record(ids.EffectType.FAME_DEFENSE_BONUS) is d.effect_types[0]
        assert d.record(ids.Currency.KT) is d.record(ids.CurrencyId.KT) is d.currencies[1]
        assert d.record(ids.General.TORIL) is d.generals[101]
        assert d.record(ids.GeneralAbility.POWER_SURGE_L1) is d.general_abilities[10011]
        assert d.record(ids.GeneralSkill.TORIL_ASPECTOFTHE_DRAGON_L1) is d.general_skills[10110201]
        assert d.record(ids.LegendSkill.GATE_REDUCTION_T0_G1_L1) is d.legend_skills[1]
        assert d.record(ids.RaidBoss.NECROMANCER) is d.raid_bosses[1]
        assert d.record(ids.GlobalEffect.SPEED_BOOST_11) is d.global_effects[11]
        assert d.record(ids.ConstructionItem.BARRACKS_COST_G1_L1) is d.construction_items[1]
        assert isinstance(d.record(ids.Unit.MEAD_RANGER_L6), UnitStats)

    def test_a_fortification_building_gives_its_model(self, lookup_data):
        assert lookup_data.record(ids.Building.CASTLEWALL_L1) is lookup_data.fortifications[501]

    def test_an_unmodeled_table_gives_the_items_row(self, lookup_data):
        d = lookup_data
        assert d.record(ids.Building.KEEP_L1) == IDS_PAYLOAD["buildings"][0]
        assert d.record(ids.Research.RECRUITMENT_SPEED_G41_L1) == IDS_PAYLOAD["researches"][1]
        assert d.record(ids.Event.NOMAD_INVASION) == IDS_PAYLOAD["events"][0]
        assert d.record(ids.LootBox.MYSTERY_BOX_BRONZE_R1) == IDS_PAYLOAD["lootBoxes"][0]
        assert d.record(ids.EquipmentGroup.ATTACK_PVP) == IDS_PAYLOAD["equipment_groups"][0]
        assert d.record(ids.DifficultyType.EASY_PLUS) == IDS_PAYLOAD["eventAutoScalingDifficultyTypes"][0]

    def test_an_id_the_data_lacks_is_none(self, lookup_data):
        assert lookup_data.record(ids.Unit.VETERAN_SABERSLASHER) is None
        assert lookup_data.record(ids.Currency.GXP1) is None
        assert lookup_data.record(next(r for r in ids.Research if r not in (1, 256))) is None
        assert GameData(version="0").record(ids.Building.KEEP_L1) is None

    def test_records_keep_the_order_across_enums(self, lookup_data):
        d = lookup_data
        missing = next(e for e in ids.Event if e not in (5, 6, 74))
        found = d.records(iter([ids.Building.KEEP_L1, ids.Unit.MEAD_RANGER_L6, ids.Currency.KT, missing]))
        assert found == [IDS_PAYLOAD["buildings"][0], d.units[211], d.currencies[1], None]
        assert d.records([]) == []

    def test_members_of_one_value_in_two_enums_stay_apart(self, lookup_data):
        # Equal ints that hash alike, which is why records is a list, not a dict
        d = lookup_data
        same = [ids.CurrencyId.KT, ids.Effect.FAME_DEFENSE_BONUS, ids.RaidBoss.NECROMANCER, ids.LegendSkill(1)]
        assert len(set(same)) == 1
        assert d.records(same) == [d.currencies[1], d.effects[1], d.raid_bosses[1], d.legend_skills[1]]

    @pytest.mark.parametrize("member", [211, "KT", Kingdom.GREEN, None])
    def test_anything_but_an_id_member_is_refused(self, lookup_data, member):
        with pytest.raises(TypeError, match="not a member of an empire_core.gamedata.ids enum"):
            lookup_data.record(member)

    def test_a_currency_member_is_one_member_not_its_letters(self, lookup_data):
        assert lookup_data.records([ids.Currency.KT]) == [lookup_data.currencies[1]]
        with pytest.raises(TypeError):
            lookup_data.records(ids.Currency.KT)

    def test_every_enum_has_a_lookup(self):
        data = GameData(version="0")
        for enum in ENUMS:
            assert data.record(next(iter(enum))) is None, enum.__name__

    def test_records_survive_the_cache(self, lookup_data, tmp_path):
        cache = tmp_path / "items.trimmed.json"
        lookup_data._write_cache(cache)
        again = GameData._read_cache(cache, lookup_data.version)
        assert again is not None
        members = [
            ids.Unit.MEAD_RANGER_L6,
            ids.Currency.KT,
            ids.Building.KEEP_L1,
            ids.Building.CASTLEWALL_L1,
            ids.Research.RECRUITMENT_SPEED_G41_L1,
            ids.Event.NOMAD_INVASION,
            ids.LootBox.MYSTERY_BOX_BRONZE_R1,
            ids.EquipmentGroup.ATTACK_PVP,
            ids.DifficultyType.EASY_PLUS,
        ]
        assert again.records(members) == lookup_data.records(members)
        assert all(record is not None for record in again.records(members))
        assert set(again.buildings) == {171, 172, 301, 401, 501}

    def test_the_fingerprint_covers_the_game_data_tables(self, monkeypatch):
        # A cache from before a table was added reads back with it empty, so every record would be None
        from empire_core.gamedata import data as module

        before = module._schema_fingerprint()

        class Wider(GameData):
            added: dict[int, dict] = {}

        monkeypatch.setattr(module, "GameData", Wider)
        assert module._schema_fingerprint() != before
        monkeypatch.undo()
        monkeypatch.setitem(module.ROW_TABLES, "events", ("events", "otherID"))
        assert module._schema_fingerprint() != before


class TestRowsById:
    def test_rows_are_keyed_by_parse_int_of_their_id(self):
        rows = [{"eventID": "x", "eventType": "Nomad"}, "junk", {"eventID": "3", "eventType": "Faction"}]
        rows += [{"eventType": "NoId"}, {"eventID": "0", "eventType": "Zero"}, {"eventID": "7abc"}]
        # "0" is truthy text in JavaScript, so 0 is an id; "7abc" reads as 7
        assert rows_by_id(rows, "eventID") == {3: rows[2], 0: rows[4], 7: rows[5]}

    def test_the_last_of_two_rows_with_one_id_is_kept(self):
        rows = [{"eventID": "3", "eventType": "A"}, {"eventID": 3, "eventType": "B"}]
        assert rows_by_id(rows, "eventID") == {3: rows[1]}

    def test_a_table_that_is_not_a_list_is_empty(self):
        assert rows_by_id({"eventID": "3"}, "eventID") == {}
        assert rows_by_id(None, "eventID") == {}

    def test_parse_keeps_every_row_table(self):
        data = GameData.parse(ids.ITEMS_VERSION, IDS_PAYLOAD)
        for field, (table, _) in ROW_TABLES.items():
            assert list(getattr(data, field).values()) == IDS_PAYLOAD[table], field


class TestGenerator:
    @pytest.fixture
    def items(self) -> GameData:
        return GameData.parse("786.03", IDS_PAYLOAD)

    def members(self, items: GameData, enum: str) -> dict[str, object]:
        table = next(t for t in gen.tables(items) if t.enum == enum)
        return dict(gen.members(table))

    @pytest.mark.parametrize(
        "text, expected",
        [
            ("MeadRanger", "MEAD_RANGER"),
            ("CooldownReductionRBC", "COOLDOWN_REDUCTION_RBC"),
            ("relicOffensiveMeleeBonusPVP", "RELIC_OFFENSIVE_MELEE_BONUS_PVP"),
            ("DecoCatalyst1", "DECO_CATALYST1"),
        ],
    )
    def test_camel_case_becomes_upper_snake(self, text, expected):
        assert gen.to_snake(text) == expected

    def test_identifiers_are_valid_and_public(self):
        assert gen.identifier("3rd place!", "U") == "U_3RD_PLACE"
        assert gen.identifier("", "U") == "U"
        assert gen.identifier("a-b  c", "U") == "A_B_C"
        assert gen.identifier("None", "U") == "NONE"

    def test_units_carry_their_level_and_colliding_ones_their_id(self, items):
        assert self.members(items, "Unit") == {
            "OGERMACE_7": 7,
            "OGERMACE_68": 68,
            "MEAD_RANGER_L6": 211,
            "MEAD_RANGER_L7": 212,
        }
        assert self.members(items, "Tool") == {
            "ELITE_COMBO_RAM_113": 113,
            "ELITE_COMBO_RAM_564": 564,
            "PREMIUMSTAKES_L2": 646,
        }

    def test_every_member_of_a_colliding_group_is_suffixed(self, items):
        assert self.members(items, "GlobalEffect") == {
            "COOLDOWN_REDUCTION_RBC": 1,
            "SPEED_BOOST_2": 2,
            "SPEED_BOOST_11": 11,
        }

    def test_skills_name_their_general_and_level(self, items):
        assert self.members(items, "GeneralSkill") == {
            "TORIL_ASPECTOFTHE_DRAGON_L1": 10110201,
            "TORIL_ASPECTOFTHE_DRAGON_L2": 10110202,
            "G102_ASPECTOFTHE_DRAGON_L1": 10210201,
        }
        assert self.members(items, "GeneralAbility") == {"POWER_SURGE_L1": 10011, "POWER_SURGE_L2": 10012}
        assert self.members(items, "LegendSkill") == {"GATE_REDUCTION_T0_G1_L1": 1, "GATE_REDUCTION_T0_G1_L2": 2}

    def test_new_tables_are_named_from_their_name_columns(self, items):
        assert self.members(items, "Building") == {
            "KEEP_L1": 171,
            "KEEP_L2": 172,
            "DECO_SUPPLIES1_L1": 301,
            "GUARD_L0": 401,
            "CASTLEWALL_L1": 501,
        }
        assert self.members(items, "Research") == {"REKRUTIERUNGSGESCHW_G1_L1": 1, "RECRUITMENT_SPEED_G41_L1": 256}
        assert self.members(items, "Event") == {"NOMAD_INVASION": 5, "PAYMENTREWARD_6": 6, "PAYMENTREWARD_74": 74}
        assert self.members(items, "LootBox") == {"MYSTERY_BOX_BRONZE_R1": 1}
        assert self.members(items, "EquipmentGroup") == {"ATTACK_PVP": 102}
        assert self.members(items, "DifficultyType") == {"EASY_PLUS": 2}
        assert self.members(items, "ConstructionItem") == {"BARRACKS_COST_G1_L1": 1}

    def test_research_names_are_unique_by_group_and_level(self):
        # Two groups share a note; group and level keep them apart, and a row without a note still gets a name
        payload = {
            "researches": [
                {"researchID": "10", "comment2": "Refined Lumber", "groupID": "7", "level": "1"},
                {"researchID": "11", "comment2": "Refined Lumber", "groupID": "8", "level": "1"},
                {"researchID": "12", "groupID": "9", "level": "2"},
            ]
        }
        table = next(t for t in gen.tables(GameData.parse("786.03", payload)) if t.enum == "Research")
        assert dict(gen.members(table)) == {
            "REFINED_LUMBER_G7_L1": 10,
            "REFINED_LUMBER_G8_L1": 11,
            "RESEARCH_G9_L2": 12,
        }
        assert gen.collided(table) == 0

    def test_currencies_by_key_and_by_id_share_names(self, items):
        assert self.members(items, "Currency") == {"KT": "KT", "DD": "DD"}
        assert self.members(items, "CurrencyId") == {"KT": 1, "DD": 100000}

    def test_output_is_deterministic_and_importable(self, items, tmp_path, monkeypatch):
        first = gen.render(items)
        reversed_payload = {key: list(reversed(rows)) for key, rows in IDS_PAYLOAD.items()}
        assert gen.render(GameData.parse("786.03", reversed_payload)) == first

        package = tmp_path / "fake_ids"
        gen.write(first, package)
        spec = importlib.util.spec_from_file_location(
            "fake_ids", package / "__init__.py", submodule_search_locations=[str(package)]
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        monkeypatch.setitem(sys.modules, "fake_ids", module)
        spec.loader.exec_module(module)
        assert module.GlobalEffect.SPEED_BOOST_11 == 11
        assert issubclass(module.Currency, str) and issubclass(module.Currency, Enum)
        assert module.ITEMS_VERSION == "786.03"

    def test_output_is_ruff_clean(self, items, tmp_path):
        ruff = shutil.which("ruff")
        if ruff is None:
            pytest.skip("ruff is not installed")
            return
        files = gen.render(items)
        long_name = "A" * 90
        wide = gen.Table(
            "wide",
            "Wide",
            "W",
            "Rows too long for one line.",
            "none",
            [
                gen.Row(long_name, 1, "1", ("x" * 40, 2)),
                gen.Row("SHORT", 2, "2", ("y", 3)),
                gen.Row("QUOTED", 3, "3", ('say "hi" and \'bye\' "now"', 4)),
                gen.Row("APOSTROPHE", 4, "4", ("it's a \\ path", 5)),
            ],
            (gen.Attr("first_column_with_a_long_name", "str", "Long."), gen.Attr("second_long_column", "int", "Too.")),
        )
        plain = gen.Table("plain", "Plain", "P", "No columns.", "none", [gen.Row("ONLY", 1, "1")])
        files["wide.py"] = gen.render_module("786.03", [(wide, gen.members(wide)), (plain, gen.members(plain))])
        files["plain.py"] = gen.render_module("786.03", [(plain, gen.members(plain))])
        assert "__new__" not in files["plain.py"] and "    ONLY = 1\n" in files["plain.py"]
        assert f"    {long_name} = (\n" in files["wide.py"] and "    SHORT = 2, " in files["wide.py"]
        assert """    QUOTED = 3, 'say "hi" and \\'bye\\' "now"', 4\n""" in files["wide.py"]
        gen.write(files, tmp_path)
        subprocess.run([ruff, "format", "--check", "--config", str(ROOT / "pyproject.toml"), str(tmp_path)], check=True)
        subprocess.run([ruff, "check", "--config", str(ROOT / "pyproject.toml"), str(tmp_path)], check=True)

    def test_items_version_comes_from_the_file(self, tmp_path):
        payload = {"versionInfo": {"version": {"@value": "786.03"}}}
        assert gen.items_version(tmp_path / "whatever.json", payload) == "786.03"
        assert gen.items_version(tmp_path / "items_v785.01.json", {}) == "785.01"
        with pytest.raises(SystemExit):
            gen.items_version(tmp_path / "items.json", {})


class TestCheck:
    @pytest.fixture
    def items_file(self, tmp_path) -> Path:
        path = tmp_path / "items_v786.03.json"
        path.write_text(json.dumps(IDS_PAYLOAD))
        return path

    def run(self, items_file: Path, out: Path, *extra: str) -> int:
        return gen.main(["--items", str(items_file), "--out", str(out), *extra])

    def test_check_passes_on_what_it_would_write(self, items_file, tmp_path):
        out = tmp_path / "ids"
        assert self.run(items_file, out) == 0
        written = {path.name: path.read_text() for path in out.glob("*.py")}
        assert self.run(items_file, out, "--check") == 0
        assert {path.name: path.read_text() for path in out.glob("*.py")} == written

    @pytest.mark.parametrize("change", ["edit", "extra", "missing", "empty"])
    def test_check_fails_on_any_difference(self, items_file, tmp_path, change):
        out = tmp_path / "ids"
        if change != "empty":
            assert self.run(items_file, out) == 0
        if change == "edit":
            (out / "units.py").write_text("# edited\n")
        elif change == "extra":
            (out / "leftover.py").write_text("")
        elif change == "missing":
            (out / "events.py").unlink()
        before = {path.name: path.read_text() for path in out.glob("*.py")} if out.exists() else {}
        assert self.run(items_file, out, "--check") == 1
        after = {path.name: path.read_text() for path in out.glob("*.py")} if out.exists() else {}
        assert after == before

    def test_name_changes_against_the_committed_package(self, items_file, tmp_path):
        out = tmp_path / "ids"
        assert self.run(items_file, out) == 0
        payload = json.loads(items_file.read_text())
        payload["events"] = [
            {"eventID": "5", "eventType": "NomadAttack"},
            {"eventID": "6", "eventType": "Paymentreward"},
            {"eventID": "99", "eventType": "Brandnew"},
        ]
        payload["lootBoxes"] = []
        payload["equipment_groups"] = [{"itemGroupID": "103", "name": "AttackPVP", "wearerID": "2", "slotID": "6"}]
        items_file.write_text(json.dumps(payload))
        names, footer = tmp_path / "names.md", tmp_path / "footer.txt"
        with pytest.raises(SystemExit):
            # The generator refuses an empty table, so LootBox has to keep a row
            self.run(items_file, out, "--check")
        payload["lootBoxes"] = [{"lootBoxID": "2", "name": "MysteryBoxBronze", "rarity": "2"}]
        items_file.write_text(json.dumps(payload))
        assert self.run(items_file, out, "--check", "--diff-names", str(names), "--breaking-footer", str(footer)) == 1

        changes = gen.name_changes(gen.render(GameData.parse("786.03", payload)), out)
        assert changes.renamed == [
            ("Event.NOMAD_INVASION", "Event.NOMAD_ATTACK"),
            ("Event.PAYMENTREWARD_6", "Event.PAYMENTREWARD"),
        ]
        assert changes.removed == ["Event.PAYMENTREWARD_74", "LootBox.MYSTERY_BOX_BRONZE_R1"]
        assert changes.changed == ["EquipmentGroup.ATTACK_PVP"]
        assert changes.added == ["Event.BRANDNEW", "LootBox.MYSTERY_BOX_BRONZE_R2"]
        report = names.read_text()
        assert "### Renamed (2)" in report and "- `Event.NOMAD_INVASION` -> `Event.NOMAD_ATTACK`" in report
        assert "### Removed (2)" in report and "### Now another id (1)" in report and "### Added (2)" in report
        assert footer.read_text().startswith("BREAKING CHANGE: Event.NOMAD_INVASION is now Event.NOMAD_ATTACK; ")

    def test_an_unchanged_package_reports_no_names(self, items_file, tmp_path):
        out = tmp_path / "ids"
        assert self.run(items_file, out) == 0
        names, footer = tmp_path / "names.md", tmp_path / "footer.txt"
        assert self.run(items_file, out, "--check", "--diff-names", str(names), "--breaking-footer", str(footer)) == 0
        assert names.read_text() == "No member was added, renamed or removed.\n"
        assert footer.read_text() == ""

    @pytest.mark.parametrize("version", ["786.03\nx", "7'86", "", "786."])
    def test_a_malformed_version_is_refused(self, tmp_path, version):
        path = tmp_path / "items.json"
        path.write_text(json.dumps({**IDS_PAYLOAD, "versionInfo": {"version": {"@value": version or " "}}}))
        with pytest.raises(SystemExit, match="not dotted digits"):
            gen.main(["--items", str(path), "--out", str(tmp_path / "ids")])

    def test_the_committed_package_is_current(self):
        path = os.environ.get("EMPIRE_CORE_ITEMS_JSON")
        if not path:
            pytest.skip("EMPIRE_CORE_ITEMS_JSON is not set")
            return
        assert gen.main(["--items", path, "--check"]) == 0


class TestStaleness:
    def test_is_current(self):
        assert ids.is_current(GameData(version=ids.ITEMS_VERSION))
        assert not ids.is_current(GameData(version="0.01"))

    @pytest.fixture
    def load(self, monkeypatch, tmp_path):
        monkeypatch.setattr("empire_core.gamedata.data._warned_versions", set())
        monkeypatch.setattr("empire_core.gamedata.data.fetch_items_data", lambda version: PAYLOAD)

        def load(version: str) -> GameData:
            monkeypatch.setattr("empire_core.gamedata.data.get_items_version", lambda: version)
            return GameData.load(cache_dir=tmp_path)

        return load

    def stale_warnings(self, caplog) -> list[str]:
        return [
            r.getMessage() for r in caplog.records if "empire_core.gamedata.ids was generated from" in r.getMessage()
        ]

    def test_load_warns_once_when_the_ids_are_from_another_version(self, load, caplog):
        with caplog.at_level(logging.WARNING, logger="empire_core.gamedata.data"):
            load("0.01")
            load("0.01")

        (message,) = self.stale_warnings(caplog)
        assert "v0.01" in message and f"v{ids.ITEMS_VERSION}" in message

    def test_load_is_quiet_for_the_version_the_ids_came_from(self, load, caplog):
        with caplog.at_level(logging.WARNING, logger="empire_core.gamedata.data"):
            load(ids.ITEMS_VERSION)

        assert self.stale_warnings(caplog) == []


def test_every_combat_effect_type_is_a_generated_effect_type():
    # CombatEffectType keeps the client's EffectTypeEnum names; the generated enum is named from the table
    from empire_core.gamedata.ids import EffectType
    from empire_core.utils.enums import CombatEffectType

    missing = [member.name for member in CombatEffectType if member.value not in EffectType._value2member_map_]
    assert missing == []
