"""The generated game-data id enums and the script that writes them."""

import copy
import importlib.util
import json
import logging
import os
import pickle
import shutil
import subprocess
import sys
from enum import Enum
from pathlib import Path
from typing import Any

import pytest
from pydantic import BaseModel

from empire_core import gamedata
from empire_core.gamedata import GameData, default_cache_dir, default_game_data, ids, set_default_game_data
from empire_core.gamedata.data import CACHE_FILENAME_TEMPLATE
from empire_core.protocol.models.skills import SetGeneralAbilitiesRequest
from tests.test_gamedata import LOOKUP_PAYLOAD, PAYLOAD

ROOT = Path(__file__).resolve().parents[1]
IDS_DIR = ROOT / "src" / "empire_core" / "gamedata" / "ids"


def _load_script():
    spec = importlib.util.spec_from_file_location(
        "generate_gamedata_ids", ROOT / "scripts" / "generate_gamedata_ids.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


gen = _load_script()

ENUMS = [getattr(ids, name) for name in ids.__all__ if isinstance(getattr(ids, name), type)]

# Which GameData table each enum's values index.
TABLE_OF = {
    "Unit": "units",
    "Tool": "tools",
    "Effect": "effects",
    "EffectType": "effect_types",
    "CurrencyId": "currencies",
    "General": "generals",
    "GeneralAbility": "general_abilities",
    "GeneralSkill": "general_skills",
    "LegendSkill": "legend_skills",
    "RaidBoss": "raid_bosses",
    "GlobalEffect": "global_effects",
}


def _cached_game_data() -> GameData | None:
    cache = default_cache_dir() / CACHE_FILENAME_TEMPLATE.format(version=ids.ITEMS_VERSION)
    return GameData._read_cache(cache, ids.ITEMS_VERSION)


class TestPackage:
    def test_every_enum_is_exported_from_gamedata(self):
        assert {e.__name__ for e in ENUMS} == set(TABLE_OF) | {"Currency"}
        for enum in ENUMS:
            assert getattr(gamedata, enum.__name__) is enum
        assert gamedata.ITEMS_VERSION == ids.ITEMS_VERSION

    def test_no_member_is_an_alias(self):
        for enum in ENUMS:
            assert len(list(enum)) == len(enum.__members__), enum.__name__

    def test_every_file_names_the_version_it_came_from(self):
        header = f"# Generated by scripts/generate_gamedata_ids.py from items {ids.ITEMS_VERSION}; do not edit.\n"
        files = sorted(IDS_DIR.glob("*.py"))
        assert files
        for path in files:
            assert path.read_text().startswith(header), path.name

    def test_known_ids(self):
        assert ids.Currency.GXP1 == "GXP1"
        assert ids.General.TORIL == 101
        assert ids.Unit.MEAD_RANGER_L6 == 211
        assert (ids.GlobalEffect.SPEED_BOOST_2, ids.GlobalEffect.SPEED_BOOST_11) == (2, 11)
        assert ids.CurrencyId[ids.Currency.KT.name] == 1

    def test_the_suite_fixtures_name_the_same_ids(self):
        payload: dict[str, Any] = dict(LOOKUP_PAYLOAD)
        payload["units"] = [*payload["units"], *PAYLOAD["units"]]
        data = GameData.parse(ids.ITEMS_VERSION, payload)
        checked = 0
        for table in gen.tables(data):
            enum = getattr(ids, table.enum)
            for name, value in gen.members(table):
                if name in enum.__members__:
                    assert enum[name].value == value, f"{table.enum}.{name}"
                    checked += 1
        assert checked >= 10

    def test_every_value_is_in_the_items_data(self):
        data = _cached_game_data()
        if data is None:
            pytest.skip(f"no cached items v{ids.ITEMS_VERSION}")
            return
        for enum in ENUMS:
            if enum is ids.Currency:
                keys = {row.json_key for row in data.currencies.values()}
                assert {m.value for m in enum} <= keys
                continue
            table = getattr(data, TABLE_OF[enum.__name__])
            assert {m.value for m in enum} == set(table), enum.__name__

    def test_regenerating_from_the_same_items_changes_nothing(self):
        # The full items file is ~20 MB and not in the repo; point EMPIRE_CORE_ITEMS_JSON at it.
        path = os.environ.get("EMPIRE_CORE_ITEMS_JSON")
        if not path:
            pytest.skip("EMPIRE_CORE_ITEMS_JSON is not set")
            return
        payload = json.loads(Path(path).read_text())
        data = GameData.parse(gen.items_version(Path(path), payload), payload)
        if data.version != ids.ITEMS_VERSION:
            pytest.skip(f"{path} is items v{data.version}, not v{ids.ITEMS_VERSION}")
        committed = {file.name: file.read_text() for file in IDS_DIR.glob("*.py")}
        assert gen.render(data) == committed


@pytest.fixture
def lookup_data():
    """The lookup fixtures as the default game data, forgotten again afterwards."""
    data = GameData.parse(ids.ITEMS_VERSION, LOOKUP_PAYLOAD)
    set_default_game_data(data)
    yield data
    set_default_game_data(None)


class TestMemberData:
    def test_fixed_columns_are_baked_in(self):
        unit = ids.Unit.VETERAN_SABERSLASHER
        assert (unit.value, unit.unit_type, unit.level, unit.role) == (5, "VeteranSaberslasher", -1, "melee")
        assert (ids.Unit.MEAD_RANGER_L6.unit_type, ids.Unit.MEAD_RANGER_L6.level) == ("MeadRanger", 6)
        assert (ids.General.TORIL.row_name, ids.General.TORIL.rarity_id) == ("Toril", 4)
        assert ids.GeneralSkill.TORIL_ASPECTOFTHE_DRAGON_L1.general_id == ids.General.TORIL
        assert ids.Currency.KT.currency_id == ids.CurrencyId.KT
        assert ids.CurrencyId.KT.json_key == ids.Currency.KT

    def test_baked_columns_match_the_generated_rows(self):
        payload: dict[str, Any] = dict(LOOKUP_PAYLOAD)
        payload["units"] = [*payload["units"], *PAYLOAD["units"]]
        data = GameData.parse(ids.ITEMS_VERSION, payload)
        for table in gen.tables(data):
            enum = getattr(ids, table.enum)
            for row in table.rows:
                member = enum._value2member_map_.get(row.value)
                if member is not None:
                    assert tuple(getattr(member, a.name) for a in table.attrs) == row.attrs, member

    def test_members_are_their_values(self):
        unit, currency = ids.Unit.MEAD_RANGER_L6, ids.Currency.KT
        assert unit == 211 and hash(unit) == hash(211) and {211: "x"}[unit] == "x"
        assert currency == "KT" and hash(currency) == hash("KT")
        for member in (unit, currency):
            assert pickle.loads(pickle.dumps(member)) is member
            assert copy.copy(member) is member and copy.deepcopy(member) is member
        assert json.dumps([unit, currency]) == '[211, "KT"]'
        assert ids.Unit(211) is unit and ids.Currency("KT") is currency

    def test_members_go_on_the_wire_as_plain_values(self):
        request = SetGeneralAbilitiesRequest(GID=ids.General.TORIL, SAIDS=[[0, ids.GeneralAbility.POWER_SURGE_L1]])
        payload = request.to_payload()
        assert payload == {"GID": 101, "SAIDS": [[0, 10011]]}
        assert type(payload["GID"]) is int and type(payload["SAIDS"][0][1]) is int

        class Typed(BaseModel):
            unit: ids.Unit
            currency: ids.Currency

        typed = Typed.model_validate({"unit": 211, "currency": "KT"})
        assert typed.unit is ids.Unit.MEAD_RANGER_L6
        assert typed.model_dump(mode="json") == {"unit": 211, "currency": "KT"}

    def test_game_data_lookups_take_members(self, lookup_data):
        assert lookup_data.get_unit(ids.Unit.MEAD_RANGER_L6) is lookup_data.units[211]
        assert lookup_data.currency(ids.Currency.KT) is lookup_data.currencies[1]
        assert lookup_data.generals.get(ids.General.TORIL) is lookup_data.generals[101]


class TestLinks:
    def test_properties_read_the_default_game_data(self, lookup_data):
        assert ids.Unit.MEAD_RANGER_L6.stats is lookup_data.units[211]
        assert ids.Tool.ELITE_COMBO_RAM_113.stats is lookup_data.tools[113]
        assert ids.General.TORIL.info is lookup_data.generals[101]
        assert ids.GeneralAbility.POWER_SURGE_L1.info is lookup_data.general_abilities[10011]
        assert ids.GeneralSkill.TORIL_ASPECTOFTHE_DRAGON_L1.info is lookup_data.general_skills[10110201]
        assert ids.LegendSkill.GATE_REDUCTION_T0_G1_L1.info is lookup_data.legend_skills[1]
        assert ids.Currency.KT.info is ids.CurrencyId.KT.info is lookup_data.currencies[1]
        assert ids.EffectType.FAME_DEFENSE_BONUS.info is lookup_data.effect_types[0]
        assert ids.RaidBoss.NECROMANCER.info is lookup_data.raid_bosses[1]
        assert ids.GlobalEffect.SPEED_BOOST_11.info is lookup_data.global_effects[11]

    def test_a_row_the_data_lacks_is_none(self, lookup_data):
        assert ids.Unit.VETERAN_SABERSLASHER.stats is None
        assert ids.Currency.GXP1.info is None

    def test_the_first_use_loads_and_keeps_the_game_data(self, monkeypatch, tmp_path):
        monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
        monkeypatch.setattr("empire_core.gamedata.data.get_items_version", lambda: ids.ITEMS_VERSION)
        fetched: list[str] = []

        def fetch(version: str) -> dict:
            fetched.append(version)
            return LOOKUP_PAYLOAD

        monkeypatch.setattr("empire_core.gamedata.data.fetch_items_data", fetch)
        set_default_game_data(None)
        try:
            assert ids.General.TORIL.info is not None
            assert ids.Unit.MEAD_RANGER_L6.stats is default_game_data().units[211]
        finally:
            set_default_game_data(None)
        assert fetched == [ids.ITEMS_VERSION]

    def test_the_enums_load_lazily(self):
        code = (
            "import sys, empire_core, empire_core.gamedata as g\n"
            "assert 'empire_core.gamedata.ids' not in sys.modules\n"
            "g.Unit\n"
            "assert 'empire_core.gamedata.ids' in sys.modules\n"
        )
        subprocess.run([sys.executable, "-c", code], check=True)


class TestGenerator:
    @pytest.fixture
    def data(self) -> GameData:
        return GameData.parse("786.03", LOOKUP_PAYLOAD)

    def members(self, data: GameData, enum: str) -> dict[str, object]:
        table = next(t for t in gen.tables(data) if t.enum == enum)
        return dict(gen.members(table))

    @pytest.mark.parametrize(
        "text, expected",
        [
            ("MeadRanger", "MEAD_RANGER"),
            ("CooldownReductionRBC", "COOLDOWN_REDUCTION_RBC"),
            ("relicOffensiveMeleeBonusPVP", "RELIC_OFFENSIVE_MELEE_BONUS_PVP"),
            ("DecoCatalyst1", "DECO_CATALYST1"),
        ],
    )
    def test_camel_case_becomes_upper_snake(self, text, expected):
        assert gen.to_snake(text) == expected

    def test_identifiers_are_valid_and_public(self):
        assert gen.identifier("3rd place!", "U") == "U_3RD_PLACE"
        assert gen.identifier("", "U") == "U"
        assert gen.identifier("a-b  c", "U") == "A_B_C"
        assert gen.identifier("None", "U") == "NONE"

    def test_units_carry_their_level_and_colliding_ones_their_id(self, data):
        assert self.members(data, "Unit") == {
            "OGERMACE_7": 7,
            "OGERMACE_68": 68,
            "MEAD_RANGER_L6": 211,
            "MEAD_RANGER_L7": 212,
        }
        assert self.members(data, "Tool") == {
            "ELITE_COMBO_RAM_113": 113,
            "ELITE_COMBO_RAM_564": 564,
            "PREMIUMSTAKES_L2": 646,
        }

    def test_every_member_of_a_colliding_group_is_suffixed(self, data):
        assert self.members(data, "GlobalEffect") == {
            "COOLDOWN_REDUCTION_RBC": 1,
            "SPEED_BOOST_2": 2,
            "SPEED_BOOST_11": 11,
        }

    def test_skills_name_their_general_and_level(self, data):
        assert self.members(data, "GeneralSkill") == {
            "TORIL_ASPECTOFTHE_DRAGON_L1": 10110201,
            "TORIL_ASPECTOFTHE_DRAGON_L2": 10110202,
            "G102_ASPECTOFTHE_DRAGON_L1": 10210201,
        }
        assert self.members(data, "GeneralAbility") == {"POWER_SURGE_L1": 10011, "POWER_SURGE_L2": 10012}
        assert self.members(data, "LegendSkill") == {"GATE_REDUCTION_T0_G1_L1": 1, "GATE_REDUCTION_T0_G1_L2": 2}

    def test_currencies_by_key_and_by_id_share_names(self, data):
        assert self.members(data, "Currency") == {"KT": "KT", "DD": "DD"}
        assert self.members(data, "CurrencyId") == {"KT": 1, "DD": 100000}

    def test_output_is_deterministic_and_importable(self, data, tmp_path, monkeypatch):
        first = gen.render(data)
        tables: dict[str, Any] = LOOKUP_PAYLOAD
        reversed_payload = {key: list(reversed(rows)) for key, rows in tables.items()}
        assert gen.render(GameData.parse("786.03", reversed_payload)) == first

        package = tmp_path / "fake_ids"
        gen.write(first, package)
        spec = importlib.util.spec_from_file_location(
            "fake_ids", package / "__init__.py", submodule_search_locations=[str(package)]
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        monkeypatch.setitem(sys.modules, "fake_ids", module)
        spec.loader.exec_module(module)
        assert module.GlobalEffect.SPEED_BOOST_11 == 11
        assert issubclass(module.Currency, str) and issubclass(module.Currency, Enum)
        assert module.ITEMS_VERSION == "786.03"

    def test_output_is_ruff_clean(self, data, tmp_path):
        ruff = shutil.which("ruff")
        if ruff is None:
            pytest.skip("ruff is not installed")
            return
        files = gen.render(data)
        long_name = "A" * 90
        wide = gen.Table(
            "wide",
            "Wide",
            "W",
            "Rows too long for one line.",
            "none",
            [gen.Row(long_name, 1, "1", ("x" * 40, 2)), gen.Row("SHORT", 2, "2", ("y", 3))],
            (gen.Attr("first_column_with_a_long_name", "str", "Long."), gen.Attr("second_long_column", "int", "Too.")),
            (gen.Link("info", "UnitStats", "get_unit", "Linked."),),
        )
        files["wide.py"] = gen.render_module("786.03", [(wide, gen.members(wide))])
        assert f"    {long_name} = (\n" in files["wide.py"] and "    SHORT = 2, " in files["wide.py"]
        gen.write(files, tmp_path)
        subprocess.run([ruff, "format", "--check", "--config", str(ROOT / "pyproject.toml"), str(tmp_path)], check=True)
        subprocess.run([ruff, "check", "--config", str(ROOT / "pyproject.toml"), str(tmp_path)], check=True)

    def test_items_version_comes_from_the_file(self, tmp_path):
        payload = {"versionInfo": {"version": {"@value": "786.03"}}}
        assert gen.items_version(tmp_path / "whatever.json", payload) == "786.03"
        assert gen.items_version(tmp_path / "items_v785.01.json", {}) == "785.01"
        with pytest.raises(SystemExit):
            gen.items_version(tmp_path / "items.json", {})


class TestStaleness:
    def test_is_current(self):
        assert ids.is_current(GameData(version=ids.ITEMS_VERSION))
        assert not ids.is_current(GameData(version="0.01"))

    @pytest.fixture
    def load(self, monkeypatch, tmp_path):
        monkeypatch.setattr("empire_core.gamedata.data._warned_versions", set())
        monkeypatch.setattr("empire_core.gamedata.data.fetch_items_data", lambda version: PAYLOAD)

        def load(version: str) -> GameData:
            monkeypatch.setattr("empire_core.gamedata.data.get_items_version", lambda: version)
            return GameData.load(cache_dir=tmp_path)

        return load

    def stale_warnings(self, caplog) -> list[str]:
        return [
            r.getMessage() for r in caplog.records if "empire_core.gamedata.ids was generated from" in r.getMessage()
        ]

    def test_load_warns_once_when_the_ids_are_from_another_version(self, load, caplog):
        with caplog.at_level(logging.WARNING, logger="empire_core.gamedata.data"):
            load("0.01")
            load("0.01")

        (message,) = self.stale_warnings(caplog)
        assert "v0.01" in message and f"v{ids.ITEMS_VERSION}" in message

    def test_load_becomes_the_default(self, load):
        try:
            data = load(ids.ITEMS_VERSION)
            assert default_game_data() is data
            again = load(ids.ITEMS_VERSION)
            assert again is not data and default_game_data() is again
        finally:
            set_default_game_data(None)

    def test_load_is_quiet_for_the_version_the_ids_came_from(self, load, caplog):
        with caplog.at_level(logging.WARNING, logger="empire_core.gamedata.data"):
            load(ids.ITEMS_VERSION)

        assert self.stale_warnings(caplog) == []


def test_every_combat_effect_type_is_a_generated_effect_type():
    # CombatEffectType keeps the client's EffectTypeEnum names; the generated enum is named from the table
    from empire_core.gamedata.ids import EffectType
    from empire_core.utils.enums import CombatEffectType

    missing = [member.name for member in CombatEffectType if member.value not in EffectType._value2member_map_]
    assert missing == []
