"""Running server events, their scoreboards, and their in-game titles (:func:`get_event_titles`)."""

from typing import TYPE_CHECKING

from empire_core.enums import RankingType
from empire_core.utils.lazy import lazy_exports

from .models import (
    EVENT_CLASSES,
    EVENT_SCOREBOARDS,
    POINT_EVENTS,
    AlienInvasionEvent,
    AllianceBonusEvent,
    AllianceMobilizationEvent,
    AllianceTournamentEvent,
    ArtifactEvent,
    BeggingKnightsEvent,
    BerimondEvent,
    CampaignEvent,
    CampaignQuestEvent,
    DiscountSaleEvent,
    DonationEvent,
    EventPart,
    EventScore,
    EventScores,
    FactionInvasionEvent,
    FameBoosterEvent,
    FortuneTellerEvent,
    GachaEvent,
    GameEvent,
    GetEventPointsRequest,
    GetEventPointsResponse,
    GiftEvent,
    GlobalEffectBoost,
    GlobalEffectBuffEvent,
    GlobalEffectEvent,
    GlobalEffectTimer,
    InvasionEvent,
    KingdomsLeagueEvent,
    LeagueScoredEvent,
    LongTermPointEvent,
    LuckyWheelEvent,
    NomadInvasionEvent,
    PointEvent,
    RaidBossEvent,
    SamuraiInvasionEvent,
    Scoreboard,
    ScoredEvent,
    SeasonEvent,
    SkipForFreeEvent,
    SpecialEvent,
    SpecialEventInfoRequest,
    TempServerEvent,
    TournamentEvent,
    TournamentRank,
)
from .service import EventsService
from .titles import get_event_titles

if TYPE_CHECKING:
    from empire_core.gamedata import Event, GlobalEffect, QuestId, RaidBoss

__all__ = [
    "EVENT_CLASSES",
    "EVENT_SCOREBOARDS",
    "POINT_EVENTS",
    "AlienInvasionEvent",
    "AllianceBonusEvent",
    "AllianceMobilizationEvent",
    "AllianceTournamentEvent",
    "ArtifactEvent",
    "BeggingKnightsEvent",
    "BerimondEvent",
    "CampaignEvent",
    "CampaignQuestEvent",
    "DiscountSaleEvent",
    "DonationEvent",
    "EventPart",
    "EventScore",
    "EventScores",
    "FactionInvasionEvent",
    "FameBoosterEvent",
    "FortuneTellerEvent",
    "GachaEvent",
    "GameEvent",
    "GetEventPointsRequest",
    "GetEventPointsResponse",
    "GiftEvent",
    "GlobalEffectBoost",
    "GlobalEffectBuffEvent",
    "GlobalEffectEvent",
    "GlobalEffectTimer",
    "InvasionEvent",
    "KingdomsLeagueEvent",
    "LeagueScoredEvent",
    "LongTermPointEvent",
    "LuckyWheelEvent",
    "NomadInvasionEvent",
    "PointEvent",
    "RaidBossEvent",
    "SamuraiInvasionEvent",
    "Scoreboard",
    "ScoredEvent",
    "SeasonEvent",
    "SkipForFreeEvent",
    "SpecialEvent",
    "SpecialEventInfoRequest",
    "TempServerEvent",
    "TournamentEvent",
    "TournamentRank",
    "EventsService",
    "get_event_titles",
    "RankingType",
    "Event",
    "GlobalEffect",
    "QuestId",
    "RaidBoss",
]


if not TYPE_CHECKING:
    __getattr__ = lazy_exports(__name__, "empire_core.gamedata.ids", ("Event", "GlobalEffect", "QuestId", "RaidBoss"))
