"""Static game data: unit and tool stats, effects, NPC camp defenses, and id enums."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .ids import (
        ITEMS_VERSION,
        Building,
        ConstructionItem,
        Currency,
        CurrencyId,
        DifficultyType,
        Effect,
        EffectType,
        EquipmentGroup,
        Event,
        General,
        GeneralAbility,
        GeneralSkill,
        GlobalEffect,
        LegendSkill,
        LootBox,
        RaidBoss,
        Research,
        Tool,
        Unit,
        is_current,
    )

from .data import CAMP_TABLES, RAW_TABLES, GameData, default_cache_dir, default_game_data, set_default_game_data
from .models import (
    AllianceBuffDef,
    AttackSlotDef,
    ConstructionItemDef,
    CurrencyDef,
    DefaultLordDef,
    DungeonDefence,
    EffectCapDef,
    EffectDef,
    EffectTypeDef,
    EquipmentEffectDef,
    FortificationDef,
    GemDef,
    GeneralAbilityDef,
    GeneralDef,
    GeneralSkillDef,
    GlobalEffectDef,
    HorseStats,
    LegendSkillDef,
    NpcCampDefence,
    RaidBossDef,
    RelicEffectDef,
    SceatSkillDef,
    ToolCategoryDef,
    ToolStats,
    UnitStats,
    parse_ids,
    parse_stacks,
)

__all__ = [
    "Building",
    "ConstructionItem",
    "DifficultyType",
    "EquipmentGroup",
    "Event",
    "LootBox",
    "Research",
    "Currency",
    "CurrencyId",
    "Effect",
    "EffectType",
    "General",
    "GeneralAbility",
    "GeneralSkill",
    "GlobalEffect",
    "ITEMS_VERSION",
    "is_current",
    "LegendSkill",
    "RaidBoss",
    "Tool",
    "Unit",
    "AllianceBuffDef",
    "AttackSlotDef",
    "ConstructionItemDef",
    "CurrencyDef",
    "FortificationDef",
    "GeneralSkillDef",
    "GlobalEffectDef",
    "SceatSkillDef",
    "CAMP_TABLES",
    "DefaultLordDef",
    "DungeonDefence",
    "EffectCapDef",
    "EffectDef",
    "EffectTypeDef",
    "EquipmentEffectDef",
    "GameData",
    "GemDef",
    "GeneralAbilityDef",
    "GeneralDef",
    "HorseStats",
    "LegendSkillDef",
    "NpcCampDefence",
    "RAW_TABLES",
    "RaidBossDef",
    "RelicEffectDef",
    "ToolCategoryDef",
    "ToolStats",
    "UnitStats",
    "default_cache_dir",
    "default_game_data",
    "set_default_game_data",
    "parse_ids",
    "parse_stacks",
]

_IDS = frozenset(
    {
        "Building",
        "ConstructionItem",
        "Currency",
        "CurrencyId",
        "DifficultyType",
        "Effect",
        "EffectType",
        "EquipmentGroup",
        "Event",
        "General",
        "GeneralAbility",
        "GeneralSkill",
        "GlobalEffect",
        "ITEMS_VERSION",
        "LegendSkill",
        "LootBox",
        "RaidBoss",
        "Research",
        "Tool",
        "Unit",
        "is_current",
    }
)


def __getattr__(name: str) -> object:
    # The id enums hold thousands of members, so they load on first use
    if name in _IDS:
        from . import ids

        return getattr(ids, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
