"""Static game data: unit and tool stats, effects, NPC camp defenses, and id enums."""

from typing import TYPE_CHECKING

from empire_core.enums import (
    BuildingGroundType,
    BuildingGroup,
    PlayerRelation,
    QuestConditionType,
    RelicEffectType,
    TitleDisplayType,
    ToolCategory,
    ToolSide,
    UnitRole,
)

if TYPE_CHECKING:
    from .ids import (
        ITEMS_VERSION,
        Achievement,
        AllianceCrestColor,
        AllianceCrestLayout,
        Building,
        ConstructionItem,
        Currency,
        CurrencyId,
        DailyQuestId,
        DifficultyType,
        Effect,
        EffectType,
        EquipmentGroup,
        Event,
        Gem,
        General,
        GeneralAbility,
        GeneralSkill,
        GlobalEffect,
        Horse,
        LegendSkill,
        LootBox,
        LootBoxType,
        MainQuest,
        QuestId,
        RaidBoss,
        Research,
        SceatSkill,
        Title,
        Tool,
        Unit,
        is_current,
    )

from .cdn import fetch_items_data, get_items_version
from .collectables import Collectable, CollectableObject, CollectableRows, CurrencyAmounts, CurrencyIdRows
from .data import CAMP_TABLES, RAW_TABLES, GameData, default_cache_dir
from .effect_texts import EffectTemplate, describe_effect, describe_effects
from .lenient import EnumOrInt, EnumOrStr, GameDataId, GameDataKey
from .models import (
    AllianceBuffDef,
    AttackSlotDef,
    ConstructionItemDef,
    CurrencyDef,
    DefaultLordDef,
    DungeonDefence,
    EffectCapDef,
    EffectDef,
    EffectTypeDef,
    EffectValue,
    EquipmentEffectDef,
    EquipmentEffectValue,
    EquipmentSetDef,
    EventCampDef,
    FortificationDef,
    GemDef,
    GeneralAbilityDef,
    GeneralDef,
    GeneralSkillDef,
    GlobalEffectDef,
    HorseStats,
    LeagueBracketDef,
    LegendSkillDef,
    NpcCampDefence,
    RaidBossDef,
    RelicEffectDef,
    SceatSkillDef,
    ToolCategoryDef,
    ToolStats,
    UnitStats,
    VipLevelDef,
    parse_ids,
    parse_stacks,
)
from .stacks import (
    EMPTY_SLOT,
    EMPTY_WOD_ID,
    SupportToolSlots,
    UnitOrTool,
    WodAmount,
    WodAmountMapping,
    WodAmounts,
    WodAmountSlots,
    wod_amount_pairs,
)
from .table import Table
from .tables import (
    AchievementCondition,
    AchievementDef,
    AllianceCrestColorDef,
    AllianceCrestLayoutDef,
    BuildingDef,
    DailyQuestDef,
    DifficultyTypeDef,
    EquipmentGroupDef,
    EventDef,
    LootBoxDef,
    LootBoxTypeDef,
    QuestCondition,
    QuestDef,
    ResearchDef,
    RewardDef,
    RewardId,
    ScalingCampDef,
    TitleDef,
)
from .troops import count_troops, get_troop_ids, troop_data_available

__all__ = [
    "BuildingGroundType",
    "BuildingGroup",
    "PlayerRelation",
    "QuestConditionType",
    "RelicEffectType",
    "TitleDisplayType",
    "ToolCategory",
    "ToolSide",
    "UnitRole",
    "Collectable",
    "CollectableObject",
    "CollectableRows",
    "CurrencyAmounts",
    "CurrencyIdRows",
    "EMPTY_SLOT",
    "EMPTY_WOD_ID",
    "SupportToolSlots",
    "UnitOrTool",
    "WodAmount",
    "WodAmountMapping",
    "WodAmountSlots",
    "WodAmounts",
    "wod_amount_pairs",
    "EnumOrInt",
    "EnumOrStr",
    "GameDataId",
    "GameDataKey",
    "count_troops",
    "fetch_items_data",
    "get_items_version",
    "get_troop_ids",
    "troop_data_available",
    "Achievement",
    "AllianceCrestColor",
    "AllianceCrestLayout",
    "Building",
    "ConstructionItem",
    "DifficultyType",
    "Gem",
    "Horse",
    "MainQuest",
    "SceatSkill",
    "Title",
    "EquipmentGroup",
    "Event",
    "LootBox",
    "LootBoxType",
    "QuestId",
    "DailyQuestId",
    "Research",
    "Currency",
    "CurrencyId",
    "Effect",
    "EffectType",
    "General",
    "GeneralAbility",
    "GeneralSkill",
    "GlobalEffect",
    "ITEMS_VERSION",
    "is_current",
    "LegendSkill",
    "RaidBoss",
    "Tool",
    "Unit",
    "AllianceBuffDef",
    "AttackSlotDef",
    "ConstructionItemDef",
    "CurrencyDef",
    "FortificationDef",
    "GeneralSkillDef",
    "GlobalEffectDef",
    "SceatSkillDef",
    "CAMP_TABLES",
    "DefaultLordDef",
    "DungeonDefence",
    "EffectCapDef",
    "EffectDef",
    "EffectTemplate",
    "EffectTypeDef",
    "EffectValue",
    "EquipmentEffectValue",
    "EquipmentEffectDef",
    "EquipmentSetDef",
    "EventCampDef",
    "GameData",
    "GemDef",
    "GeneralAbilityDef",
    "GeneralDef",
    "HorseStats",
    "LeagueBracketDef",
    "LegendSkillDef",
    "NpcCampDefence",
    "RAW_TABLES",
    "Table",
    "RaidBossDef",
    "RelicEffectDef",
    "ToolCategoryDef",
    "ToolStats",
    "UnitStats",
    "VipLevelDef",
    "AchievementCondition",
    "AchievementDef",
    "AllianceCrestColorDef",
    "AllianceCrestLayoutDef",
    "BuildingDef",
    "DailyQuestDef",
    "DifficultyTypeDef",
    "EquipmentGroupDef",
    "EventDef",
    "LootBoxDef",
    "LootBoxTypeDef",
    "QuestCondition",
    "QuestDef",
    "ResearchDef",
    "RewardDef",
    "RewardId",
    "ScalingCampDef",
    "TitleDef",
    "default_cache_dir",
    "describe_effect",
    "describe_effects",
    "parse_ids",
    "parse_stacks",
]

_IDS = frozenset(
    {
        "Achievement",
        "AllianceCrestColor",
        "AllianceCrestLayout",
        "Building",
        "ConstructionItem",
        "Currency",
        "CurrencyId",
        "DailyQuestId",
        "DifficultyType",
        "Effect",
        "EffectType",
        "EquipmentGroup",
        "Event",
        "Gem",
        "General",
        "GeneralAbility",
        "GeneralSkill",
        "GlobalEffect",
        "Horse",
        "ITEMS_VERSION",
        "LegendSkill",
        "LootBox",
        "LootBoxType",
        "MainQuest",
        "QuestId",
        "RaidBoss",
        "Research",
        "SceatSkill",
        "Title",
        "Tool",
        "Unit",
        "is_current",
    }
)


def __getattr__(name: str) -> object:
    # The id enums hold thousands of members, so they load on first use
    if name in _IDS:
        from . import ids

        return getattr(ids, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
