"""Attacks: sending, pre-calculation, presets and dungeon cooldowns."""

from empire_core.enums import AttackType, AutoSkipCooldownType, LootPriority

from .models import (
    AttackInfoResponse,
    AttackPreset,
    AttackTargetArea,
    CreateAttackRequest,
    CreateAttackResponse,
    GetAttackInfoRequest,
    GetAttackInfoResponse,
    GetBossDungeonAttackInfoRequest,
    GetBossDungeonAttackInfoResponse,
    GetCapitalConquerInfoRequest,
    GetCapitalConquerInfoResponse,
    GetDungeonAttackInfoRequest,
    GetDungeonAttackInfoResponse,
    GetIslandAttackInfoRequest,
    GetIslandAttackInfoResponse,
    GetLandmarkAttackInfoRequest,
    GetLandmarkAttackInfoResponse,
    GetMetropolConquerInfoRequest,
    GetMetropolConquerInfoResponse,
    GetOutpostConquerInfoRequest,
    GetOutpostConquerInfoResponse,
    GetPresetsRequest,
    GetPresetsResponse,
    GetVillageAttackInfoRequest,
    GetVillageAttackInfoResponse,
    MinuteSkipDungeonRequest,
    MinuteSkipDungeonResponse,
    PresetArmy,
    SavePresetRequest,
    SavePresetResponse,
    SkipDungeonCooldownRequest,
    SkipDungeonCooldownResponse,
)

__all__ = [
    "MinuteSkipDungeonRequest",
    "MinuteSkipDungeonResponse",
    "SkipDungeonCooldownRequest",
    "SkipDungeonCooldownResponse",
    "AttackTargetArea",
    "AttackInfoResponse",
    "GetAttackInfoRequest",
    "GetAttackInfoResponse",
    "GetPresetsRequest",
    "GetPresetsResponse",
    "AttackPreset",
    "PresetArmy",
    "SavePresetRequest",
    "SavePresetResponse",
    "CreateAttackRequest",
    "CreateAttackResponse",
    "GetDungeonAttackInfoRequest",
    "GetDungeonAttackInfoResponse",
    "GetBossDungeonAttackInfoRequest",
    "GetBossDungeonAttackInfoResponse",
    "GetLandmarkAttackInfoRequest",
    "GetLandmarkAttackInfoResponse",
    "GetVillageAttackInfoRequest",
    "GetVillageAttackInfoResponse",
    "GetIslandAttackInfoRequest",
    "GetIslandAttackInfoResponse",
    "GetOutpostConquerInfoRequest",
    "GetOutpostConquerInfoResponse",
    "GetCapitalConquerInfoRequest",
    "GetCapitalConquerInfoResponse",
    "GetMetropolConquerInfoRequest",
    "GetMetropolConquerInfoResponse",
    "AttackType",
    "LootPriority",
    "AutoSkipCooldownType",
]
