# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

"""
Game-data ids as enums, so they autocomplete.

One enum per items table, each member named from the row in UPPER_SNAKE;
where two rows would share a name, both carry their id (``SPEED_BOOST_2``).
Members are plain ints (``Currency`` members plain strs), so they go on the
wire and into models as their value.

Most members also carry their row's fixed id and number columns, e.g.
``Unit.MEAD_RANGER_L6.role`` and ``.level`` or ``Tool.X.category``, so
``[t for t in Tool if t.category == "Defence"]`` works without game data.
Anything a balance patch can change is not baked in: for the full row, load a
:class:`GameData` (nothing here downloads it) and ask
``game_data.record(member)``, or ``game_data.records(members)`` for several.

``ITEMS_VERSION`` is the items version they were generated from, and
:func:`is_current` says whether a loaded :class:`GameData` is that version. For
anything newer, use the named lookups on :class:`GameData`.

Gems, equipment, horses, relic effects, alliance buffs and sceat skills have
no enum, as their rows have no name; look them up by id on :class:`GameData`
(``gems``, ``equipment_effects``, ``get_horse``, ``relic_effects``,
``alliance_buffs``, ``sceat_skills``).

Regenerate with ``uv run python scripts/generate_gamedata_ids.py``.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from empire_core.gamedata.data import GameData

    from .buildings import Building
    from .construction_items import ConstructionItem
    from .currencies import Currency, CurrencyId
    from .daily_quests import DailyQuestId
    from .difficulty_types import DifficultyType
    from .effect_types import EffectType
    from .effects import Effect
    from .equipment_groups import EquipmentGroup
    from .events import Event
    from .general_abilities import GeneralAbility
    from .general_skills import GeneralSkill
    from .generals import General
    from .global_effects import GlobalEffect
    from .legend_skills import LegendSkill
    from .loot_box_types import LootBoxType
    from .loot_boxes import LootBox
    from .quests import QuestId
    from .raid_bosses import RaidBoss
    from .researches import Research
    from .tools import Tool
    from .units import Unit

ITEMS_VERSION = "786.03"
"""The items version these enums were generated from."""

# Each enum's module, imported on first use: together they hold thousands of members
_MODULES = {
    "Building": "buildings",
    "ConstructionItem": "construction_items",
    "Currency": "currencies",
    "CurrencyId": "currencies",
    "DailyQuestId": "daily_quests",
    "DifficultyType": "difficulty_types",
    "Effect": "effects",
    "EffectType": "effect_types",
    "EquipmentGroup": "equipment_groups",
    "Event": "events",
    "General": "generals",
    "GeneralAbility": "general_abilities",
    "GeneralSkill": "general_skills",
    "GlobalEffect": "global_effects",
    "LegendSkill": "legend_skills",
    "LootBox": "loot_boxes",
    "LootBoxType": "loot_box_types",
    "QuestId": "quests",
    "RaidBoss": "raid_bosses",
    "Research": "researches",
    "Tool": "tools",
    "Unit": "units",
}


def is_current(game_data: GameData) -> bool:
    """Whether ``game_data`` is the items version these enums were generated from."""
    return game_data.version == ITEMS_VERSION


if not TYPE_CHECKING:
    # Hidden from type checkers, so they still flag a name the package lacks
    def __getattr__(name: str) -> Any:
        module = _MODULES.get(name)
        if module is None:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
        value = getattr(importlib.import_module(f".{module}", __name__), name)
        globals()[name] = value
        return value

    def __dir__() -> list[str]:
        return sorted({*globals(), *__all__})


__all__ = [
    "Building",
    "ConstructionItem",
    "Currency",
    "CurrencyId",
    "DailyQuestId",
    "DifficultyType",
    "Effect",
    "EffectType",
    "EquipmentGroup",
    "Event",
    "General",
    "GeneralAbility",
    "GeneralSkill",
    "GlobalEffect",
    "ITEMS_VERSION",
    "LegendSkill",
    "LootBox",
    "LootBoxType",
    "QuestId",
    "RaidBoss",
    "Research",
    "Tool",
    "Unit",
    "is_current",
]
