# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

"""
Game-data ids as enums, so they autocomplete.

One enum per items table, each member named from the row in UPPER_SNAKE;
where two rows would share a name, both carry their id (``SPEED_BOOST_2``).
``ITEMS_VERSION`` is the items version they were generated from, and
:func:`is_current` says whether a loaded :class:`GameData` is that version. For
anything newer, use the named lookups on :class:`GameData`.

Gems, equipment and horses have no enum, as their rows have no name; look them
up by id with ``GameData.gems``, ``GameData.equipment_effects`` and
``GameData.get_horse``.

Regenerate with ``uv run python scripts/generate_gamedata_ids.py``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .currencies import Currency, CurrencyId
from .effect_types import EffectType
from .effects import Effect
from .general_abilities import GeneralAbility
from .general_skills import GeneralSkill
from .generals import General
from .global_effects import GlobalEffect
from .legend_skills import LegendSkill
from .raid_bosses import RaidBoss
from .tools import Tool
from .units import Unit

if TYPE_CHECKING:
    from empire_core.gamedata.data import GameData

ITEMS_VERSION = "786.03"
"""The items version these enums were generated from."""


def is_current(game_data: GameData) -> bool:
    """Whether ``game_data`` is the items version these enums were generated from."""
    return game_data.version == ITEMS_VERSION


__all__ = [
    "Currency",
    "CurrencyId",
    "Effect",
    "EffectType",
    "General",
    "GeneralAbility",
    "GeneralSkill",
    "GlobalEffect",
    "ITEMS_VERSION",
    "LegendSkill",
    "RaidBoss",
    "Tool",
    "Unit",
    "is_current",
]
