# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

"""
Game-data ids as enums, so they autocomplete.

One enum per items table, each member named from the row in UPPER_SNAKE;
where two rows would share a name, both carry their id (``SPEED_BOOST_2``).
Members are plain ints (``Currency`` members plain strs), so they go on the
wire and into models as their value.

Most members also carry the fixed columns of their row that the name does not
already say, e.g. ``Unit.MEAD_RANGER_L6.role`` or ``Tool.X.category``, so
``[t for t in Tool if t.category == "Defence"]`` works without game data.
Anything a balance patch can change is not baked in: for the full row, load a
:class:`GameData` (nothing here downloads it) and ask
``game_data.record(member)``, or ``game_data.records(members)`` for several.

``ITEMS_VERSION`` is the items version they were generated from, and
:func:`is_current` says whether a loaded :class:`GameData` is that version. For
anything newer, use the named lookups on :class:`GameData`.

Gems, equipment, horses, relic effects, alliance buffs and sceat skills have
no enum, as their rows have no name; look them up by id on :class:`GameData`
(``gems``, ``equipment_effects``, ``get_horse``, ``relic_effects``,
``alliance_buffs``, ``sceat_skills``).

Regenerate with ``uv run python scripts/generate_gamedata_ids.py``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .buildings import Building
from .construction_items import ConstructionItem
from .currencies import Currency, CurrencyId
from .difficulty_types import DifficultyType
from .effect_types import EffectType
from .effects import Effect
from .equipment_groups import EquipmentGroup
from .events import Event
from .general_abilities import GeneralAbility
from .general_skills import GeneralSkill
from .generals import General
from .global_effects import GlobalEffect
from .legend_skills import LegendSkill
from .loot_boxes import LootBox
from .raid_bosses import RaidBoss
from .researches import Research
from .tools import Tool
from .units import Unit

if TYPE_CHECKING:
    from empire_core.gamedata.data import GameData

ITEMS_VERSION = "786.03"
"""The items version these enums were generated from."""


def is_current(game_data: GameData) -> bool:
    """Whether ``game_data`` is the items version these enums were generated from."""
    return game_data.version == ITEMS_VERSION


__all__ = [
    "Building",
    "ConstructionItem",
    "Currency",
    "CurrencyId",
    "DifficultyType",
    "Effect",
    "EffectType",
    "EquipmentGroup",
    "Event",
    "General",
    "GeneralAbility",
    "GeneralSkill",
    "GlobalEffect",
    "ITEMS_VERSION",
    "LegendSkill",
    "LootBox",
    "RaidBoss",
    "Research",
    "Tool",
    "Unit",
    "is_current",
]
