# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum


class AllianceCrestLayout(IntEnum):
    """
    Alliance crest layout ids from the ``allianceCoatLayouts`` table, named from the game's English name, else the
    ``comment1`` note.

    Client: ``AllianceCrestLayoutVO.parseXML`` (bundle line 111024); names from
    ``CollectableItemAllianceCrestLayoutVO.getNameTextId`` (bundle line 89359)
    """

    _value_: int
    color_count: int
    """Colours it takes."""

    def __new__(cls, value: int, color_count: int = 0) -> AllianceCrestLayout:
        member = int.__new__(cls, value)
        member._value_ = value
        member.color_count = color_count
        return member

    FREE_1 = 1, 1
    FREE_2 = 2, 2
    FREE_3 = 3, 2
    FREE_4 = 4, 2
    FREE_5 = 5, 2
    FREE_6 = 6, 2
    FREE_7 = 7, 2
    FREE_8 = 8, 2
    NOMADS_WRATH_EMBLEM = 9, 2
    SAMURAIS_HONOR_EMBLEM = 10, 3
    ALIEN_MENACE_EMBLEM = 11, 3
    BLOODCROWS_FURY_EMBLEM = 12, 2
    GOLDEN_CHAMPION_EMBLEM = 13, 3
    GOLDEN_RUNNER_UP_EMBLEM = 14, 3
    GOLDEN_FINALIST_EMBLEM = 15, 3
    BRONZE_RIFT_RAID_CONQUEROR = 16, 3
    SILVER_RIFT_RAID_CONQUEROR = 17, 3
    GOLD_RIFT_RAID_CONQUEROR = 18, 3
    DIAMOND_RIFT_RAID_CONQUEROR = 19, 3


class AllianceCrestColor(IntEnum):
    """
    Alliance crest colour ids from the ``allianceCoatColors`` table. The game names no colour, so each is named by its
    id and carries its hex colour.

    Client: ``AllianceCrestColorVO.parseXML`` (bundle line 111012)
    """

    _value_: int
    color: str
    """The colour as hex text, e.g. 0xDBDACA."""

    def __new__(cls, value: int, color: str = "") -> AllianceCrestColor:
        member = int.__new__(cls, value)
        member._value_ = value
        member.color = color
        return member

    COLOR_1 = 1, "0xDBDACA"
    COLOR_2 = 2, "0x878470"
    COLOR_3 = 3, "0x4F4D46"
    COLOR_4 = 4, "0x191919"
    COLOR_5 = 5, "0x512C0A"
    COLOR_6 = 6, "0x893C27"
    COLOR_7 = 7, "0xB70000"
    COLOR_8 = 8, "0xD63212"
    COLOR_9 = 9, "0xF95B1C"
    COLOR_10 = 10, "0xDB9C0F"
    COLOR_11 = 11, "0xEFB206"
    COLOR_12 = 12, "0xE8D80F"
    COLOR_13 = 13, "0xCEC519"
    COLOR_14 = 14, "0x007730"
    COLOR_15 = 15, "0x009B67"
    COLOR_16 = 16, "0x04A8A3"
    COLOR_17 = 17, "0x4792DD"
    COLOR_18 = 18, "0x0F65BA"
    COLOR_19 = 19, "0x3D227F"
    COLOR_20 = 20, "0xCE2469"
