# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum


class DailyQuestId(IntEnum):
    """
    Daily quest ids from the ``dailyactivities`` table, named from what the first condition counts. Named DailyQuestId,
    as ``empire_core.quests.DailyQuest`` is today's quest.

    Client: ``CastleDailyQuestData.createXmlQuestDic`` (bundle line 134082), ``DailyQuestVO.fillFromParamXML`` (bundle
    line 134124)
    """

    _value_: int
    trigger_kingdom_id: int
    """The kingdom the quest counts in, a ``Kingdom`` value; -1 for any."""

    def __new__(cls, value: int, trigger_kingdom_id: int = 0) -> DailyQuestId:
        member = int.__new__(cls, value)
        member._value_ = value
        member.trigger_kingdom_id = trigger_kingdom_id
        return member

    LOGIN = 1, -1
    SPEND_C2 = 2, -1
    COLLECT_TAX = 3, -1
    RESOURCE_TO_PLAYER = 4, -1
    SPY = 5, -1
    SABOTAGE_DAMAGE = 6, -1
    COUNT_DUNGEONS_7 = 7, 0
    COUNT_DUNGEONS_8 = 8, 2
    COUNT_DUNGEONS_9 = 9, 1
    COUNT_DUNGEONS_10 = 10, 3
    USE_ALLIANCE_FORGE = 12, -1
    CRAFT_EQUIPMENT = 13, -1
    WRITE_IN_ALLIANCE_CHAT = 14, -1
    COLLECT_FROM_CITIZEN = 15, -1
    RECRUIT_UNITS = 16, -1
    PRODUCE_TOOLS = 17, -1
    REQUEST_ALLIANCE_HELP = 21, -1
    COMPLETE_MERCENARY_MISSION = 22, -1
    COLLECT_FROM_CARRIAGE = 23, -1
    COUNT_DUNGEONS_24 = 24, -1
    COUNT_BATTLES_25 = 25, -1
    COUNT_BATTLES_26 = 26, -1
