# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from enum import IntEnum


class DifficultyType(IntEnum):
    """
    Event difficulty type ids from the ``eventAutoScalingDifficultyTypes`` table.

    Client: ``EventAutoScalingDifficultyTypeVO.parseXML`` (bundle line 38258)
    """

    EASY = 1
    EASY_PLUS = 2
    INTERMEDIATE = 3
    INTERMEDIATE_PLUS = 4
    HARD = 5
    HARD_PLUS = 6
    EXPERT = 7
    EXPERT_PLUS = 8
    MASTER = 9
    MASTER_PLUS = 10
    ARCHMASTER = 11
