# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum


class DifficultyType(IntEnum):
    """
    Event difficulty type ids from the ``eventAutoScalingDifficultyTypes`` table.

    Client: ``EventAutoScalingDifficultyTypeVO.parseXML`` (bundle line 38258)
    """

    _value_: int
    row_name: str
    """The row's name column."""

    def __new__(cls, value: int, row_name: str = "") -> DifficultyType:
        member = int.__new__(cls, value)
        member._value_ = value
        member.row_name = row_name
        return member

    EASY = 1, "easy"
    EASY_PLUS = 2, "easyPlus"
    INTERMEDIATE = 3, "intermediate"
    INTERMEDIATE_PLUS = 4, "intermediatePlus"
    HARD = 5, "hard"
    HARD_PLUS = 6, "hardPlus"
    EXPERT = 7, "expert"
    EXPERT_PLUS = 8, "expertPlus"
    MASTER = 9, "master"
    MASTER_PLUS = 10, "masterPlus"
    ARCHMASTER = 11, "archmaster"
