# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum


class EquipmentGroup(IntEnum):
    """
    Equipment item group ids from the ``equipment_groups`` table, as equipment effects name them.

    Client: ``XmlEquipmentGroupVO.parseXml`` (bundle line 144187)
    """

    _value_: int
    row_name: str
    """The row's name column."""
    wearer_id: int
    """Who wears it, a ``WearerType`` value."""
    slot_id: int
    """The slot it goes in, an ``EquipmentSlot`` value."""

    def __new__(cls, value: int, row_name: str = "", wearer_id: int = 0, slot_id: int = 0) -> EquipmentGroup:
        member = int.__new__(cls, value)
        member._value_ = value
        member.row_name = row_name
        member.wearer_id = wearer_id
        member.slot_id = slot_id
        return member

    DEFENSE = 1, "Defense", 1, 6
    CONQUER_BARON = 2, "ConquerBaron", 1, 6
    AROUND_FIGHT_BARON = 3, "AroundFightBaron", 1, 6
    CONQUER_GENERAL = 101, "ConquerGeneral", 2, 6
    ATTACK_PVP = 102, "AttackPVP", 2, 6
    ATTACK_PVE = 103, "AttackPVE", 2, 6
    AROUND_FIGHT_PVP = 104, "AroundFightPVP", 2, 6
    AROUND_FIGHT_PVE = 105, "AroundFightPVE", 2, 6
    NOMAD_HERO = 151, "NomadHero", 2, 6
    WEAK_POINT_EVENT_HERO_BARON1 = 152, "WeakPointEventHeroBaron1", 1, 6
    WEAK_POINT_EVENT_HERO_BARON2 = 153, "WeakPointEventHeroBaron2", 1, 6
    WEAK_POINT_EVENT_HERO_GENERAL1 = 154, "WeakPointEventHeroGeneral1", 2, 6
    WEAK_POINT_EVENT_HERO_GENERAL2 = 155, "WeakPointEventHeroGeneral2", 2, 6
