# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from enum import IntEnum

from empire_core.texts import has_text, text


class Event(IntEnum):
    """
    Event ids from the ``events`` table, named from ``eventType``.

    Client: ``CastleSpecialEventData.storeXmlEvents`` (bundle line 139777) keys rows by ``eventID``,
    ``ASpecialEventVO.parseBasicsFromXmlNode`` (bundle line 2959) reads ``eventType``
    """

    @property
    def text_id(self) -> str:
        """The text id of its name, ``event_title_<value>``."""
        return f"event_title_{self.value}"

    def display_name(self, lang: str = "en") -> str | None:
        """
        The game's name for it in ``lang``, the text ``event_title_<value>``; None when the language file has no such
        text.

        Fetches the language file on first use and caches it (:func:`empire_core.texts.text`); a text the file lacks, or
        a failed fetch, gives the text id.

        Client: ``"event_title_" + eventID``, as the reward hub, alliance quests and season events name an event (bundle
        lines 54451, 111097 and 31389)
        """
        return text(self.text_id, lang=lang) if has_text(self.text_id, lang) else None

    THORNKING = 2
    FACTION = 3
    SEAQUEEN = 4
    NOMAD_INVASION = 5
    PAYMENTREWARD_6 = 6
    PRIME_SALE = 7
    SKIP_FOR_FREE = 8
    AWARDREWARD = 10
    ALIEN_INVASION = 11
    GGS_GIFT = 13
    UNIT_DEALER_14 = 14
    LUCKY_WHEEL = 15
    FAMEBOOSTER = 16
    UNIT_DEALER_17 = 17
    ADJUST_SKIP_BUILDING = 18
    ARTIFACT_19 = 19
    OVERSEER = 20
    SHADOW_UNIT = 21
    MERCHANT_22 = 22
    ARTIFACT_23 = 23
    TOURNAMENT = 24
    BOUNTYHUNTER = 25
    RANDOMDUNGEON_26 = 26
    ARMORER = 27
    ARTIFACT_29 = 29
    ARTIFACT_30 = 30
    ALCHEMIST = 35
    ALLI_TOURNAMENT = 36
    RENEGADE_37 = 37
    RENEGADE_38 = 38
    RENEGADE_39 = 39
    CONSTRUCTION_EXPERT = 40
    PLAGUE = 41
    MERCHANT_42 = 42
    UNIT_DEALER_43 = 43
    COLOSSUS_44 = 44
    PRIME_ALLI_BONUS = 45
    EQUIPMENT_ENHANCER = 46
    RANDOMDUNGEON_48 = 48
    NOMAD_HUNTER = 49
    RESEARCH_EXPERT = 50
    ALLI_PAYMENT_BONUS = 55
    COLOSSUS_57 = 57
    UNIT_DEALER_58 = 58
    POINT_EVENT = 60
    EVENT_SKIN = 61
    BEGGING_KNIGHTS = 62
    WORLD_CUP = 63
    UNDERWORLD = 64
    USER_SURVEY = 65
    PLAYER_GIFT_MERCHANT = 66
    ARTIFACT_67 = 67
    EVENT_PACKAGE_PRIME_SALE = 68
    COLOSSUS_69 = 69
    PRIME_SALE_REVIVE_ALL = 70
    ALLIANCE_ALIEN_INVASION = 71
    ALLIANCE_NOMAD_INVASION = 72
    EVENT_ANNOUNCEMENT = 73
    PAYMENTREWARD_74 = 74
    EVENT_BOOSTER_PRIME_SALE = 75
    FACTION_ARMORER = 76
    TEMPORARY_QUEST = 77
    PAYMENTREWARD_78 = 78
    PAYMENTREWARD_79 = 79
    SAMURAI_INVASION = 80
    SAMURAI_HUNTER = 81
    TIERED_PAYMENTREWARD = 82
    LONG_TERM_POINT_EVENT = 83
    PRIVATE_PRIME_TIME_EVENT = 84
    FACTION_INVASION = 85
    FACTION_HUNTER = 86
    EQUIPMENT_ENHANCER_PRIME_SALE = 87
    RELIC_ENCHANTER_PRIME_SALE = 88
    SALE_DAYS_LUCKY_WHEEL = 89
    SHOPPING_CART_PRIME_SALE = 90
    APPRENTICE_SMITH = 92
    WISHING_WELL_COIN_VENDOR = 93
    NOMAD_INVASION_VENDOR = 94
    TIME_LIMITED_CAMPAIGN_EVENT = 95
    TIME_LIMITED_CAMPAIGN_QUEST_EVENT = 96
    UNIT_PRIME_SALE = 100
    EQUIPMENT_MERCHANT = 101
    E102 = 102
    RED_ALLIANCE_ALIEN_INVASION = 103
    FUSION_RECHARGE_PRIME_SALE = 104
    PREMIUM_FUSION_PRIME_SALE = 105
    TEMP_SERVER = 106
    COLLECTOR_EVENT = 108
    COLLECTOR_SHOP = 109
    TEMP_SERVER_MULTIPLIER = 110
    DAIMYO_SHOP = 111
    PRIME_SALE_EXPANSION = 112
    ALLIANCE_BATTLE_GROUND = 113
    WEB_SHOP = 114
    REACTIVATION_PRIVATE_PRIME_TIME_EVENT = 115
    APPRENTICE_TOKEN_VENDOR = 116
    FORTUNE_TELLER = 117
    LOYALTY = 118
    MOBILE_BROWSER_SHOP_STANDARD = 119
    MOBILE_BROWSER_SHOP_SPECIAL = 120
    MOBILE_BROWSER_SHOP_TEMPSERVER_STANDARD = 121
    MOBILE_BROWSER_SHOP_TEMPSERVER_SPECIAL = 122
    DONATION_EVENT = 123
    PRIME_TIME_SKIN_EVENT = 124
    SPECIAL_DAILY_BUNDLE_EVENT = 125
    GACHA_DECO2X2 = 126
    CHRISTMAS_GACHA = 127
    EASTER_GACHA = 128
    ALLIANCE_MOBILIZATION_EVENT = 129
    SUMMER_GACHA = 130
    ANNIVERSARY_GACHA = 131
    HALLOWEEN_GACHA = 132
    ALLIANCE_RAIDBOSS_EVENT = 133
    BLACK_FRIDAY_GACHA = 134
    CARNIVAL_GACHA = 135
    CONVERSION_PRIVATE_PRIME_TIME_EVENT = 136
    RAIDBOSS_SHOP_EVENT = 138
    SEASON_PASS_PRIME_SALE = 599
    SEASON_LEAGUE = 601
    GLOBAL_EFFECT = 610
    KILL_GLOBAL_EFFECT = 611
    GLOBAL_EFFECT_BUFF = 612
    KILL_GLOBAL_EFFECT_BUFF = 613
