# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from enum import IntEnum


class General(IntEnum):
    """
    General ids from the ``generals`` table.

    Client: ``GeneralXmlVO.fillFromParamXml`` (bundle line 33102)
    """

    TORIL = 101
    LEO = 102
    ALYSSA = 103
    HORATIO = 104
    SASAKI = 105
    WOLF_KING = 106
    TOM = 107
    ALICE = 108
    USKHAL = 109
    SAMURAI_GENERAL = 110
    BABA_VARJUKA = 111
    ALIEN_GENERAL = 112
    RED_GENERAL = 113
    BLUE_GENERAL = 114
    ROBBER_BARON = 115
    SULTAN_AL_KILLAH = 116
    KING_OLAFSON = 117
    YIGRIS = 118
    TIZI = 119
    HASAN = 120
    DIANA = 121
    VALENTA = 122
    GARRIK = 123
    ASHIRA = 124
    KAELRITH = 125
    EDRIC = 126
    BARIN = 127
    RAID_BOSS1_FULL = 128
    RAID_BOSS1_MID = 129
    RAID_BOSS1_LOW = 130
    RAID_BOSS2_FULL = 131
    RAID_BOSS2_MID = 132
    RAID_BOSS2_LOW = 133
    RAID_BOSS3_FULL = 134
    RAID_BOSS3_MID = 135
    RAID_BOSS3_LOW = 136
