# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum

from empire_core.texts import has_text, text


class General(IntEnum):
    """
    General ids from the ``generals`` table.

    Client: ``GeneralXmlVO.fillFromParamXml`` (bundle line 33102)
    """

    _value_: int
    rarity_id: int
    """The ``generalRarityID`` column."""

    def __new__(cls, value: int, rarity_id: int = 0) -> General:
        member = int.__new__(cls, value)
        member._value_ = value
        member.rarity_id = rarity_id
        return member

    @property
    def text_id(self) -> str:
        """The text id of its name, ``generals_characters_<value>_name``."""
        return f"generals_characters_{self.value}_name"

    def display_name(self, lang: str = "en") -> str | None:
        """
        The game's name for it in ``lang``, the text ``generals_characters_<value>_name``; None when the language file
        has no such text.

        Fetches the language file on first use and caches it (:func:`empire_core.texts.text`); a text the file lacks, or
        a failed fetch, gives the text id.

        Client: ``GeneralXmlVO.nameTextID`` (bundle line 33105)
        """
        return text(self.text_id, lang=lang) if has_text(self.text_id, lang) else None

    TORIL = 101, 4
    LEO = 102, 2
    ALYSSA = 103, 2
    HORATIO = 104, 3
    SASAKI = 105, 4
    WOLF_KING = 106, 4
    TOM = 107, 1
    ALICE = 108, 1
    USKHAL = 109, 4
    SAMURAI_GENERAL = 110, 4
    BABA_VARJUKA = 111, 4
    ALIEN_GENERAL = 112, 4
    RED_GENERAL = 113, 4
    BLUE_GENERAL = 114, 4
    ROBBER_BARON = 115, 4
    SULTAN_AL_KILLAH = 116, 4
    KING_OLAFSON = 117, 4
    YIGRIS = 118, 4
    TIZI = 119, 3
    HASAN = 120, 2
    DIANA = 121, 3
    VALENTA = 122, 2
    GARRIK = 123, 1
    ASHIRA = 124, 3
    KAELRITH = 125, 4
    EDRIC = 126, 1
    BARIN = 127, 3
    RAID_BOSS1_FULL = 128, 2
    RAID_BOSS1_MID = 129, 2
    RAID_BOSS1_LOW = 130, 2
    RAID_BOSS2_FULL = 131, 1
    RAID_BOSS2_MID = 132, 1
    RAID_BOSS2_LOW = 133, 1
    RAID_BOSS3_FULL = 134, 4
    RAID_BOSS3_MID = 135, 4
    RAID_BOSS3_LOW = 136, 4
