# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum

from empire_core.gamedata.data import default_game_data
from empire_core.gamedata.models import GlobalEffectDef


class GlobalEffect(IntEnum):
    """
    Global effect ids from the ``globalEffects`` table.

    Client: ``GlobalEffectVO.parseXml`` (bundle line 143690)
    """

    _value_: int
    row_name: str
    """The row's name column."""

    def __new__(cls, value: int, row_name: str = "") -> GlobalEffect:
        member = int.__new__(cls, value)
        member._value_ = value
        member.row_name = row_name
        return member

    @property
    def info(self) -> GlobalEffectDef | None:
        """This global effect's row in the loaded game data, or None if it has none."""
        return default_game_data().global_effects.get(self)

    COOLDOWN_REDUCTION_RBC = 1, "CooldownReductionRBC"
    SPEED_BOOST_2 = 2, "SpeedBoost"
    COLLECTOR_TEMP_SERVER_BOOST = 3, "CollectorTempServerBoost"
    FOOD_CONSUMPTION_BOOST = 4, "foodConsumptionBoost"
    ATTACK_BOOST_SPEERMAN_BOWMAN = 5, "attackBoostSpeermanBowman"
    ATTACK_BOOST_MACE_CROSSBOWMAN = 6, "attackBoostMaceCrossbowman"
    ATTACK_BOOST_VALKYRIE_MELEE_VALKYRIE_RANGE = 7, "attackBoostValkyrieMeleeValkyrieRange"
    ATTACK_BOOST_MASTER_SWORDSMAN_MASTER_ARCHER = 8, "attackBoostMasterSwordsmanMasterArcher"
    ATTACK_BOOST_ELITE_RANKREWARD_MELEE_ELITE_RANKREWARD_RANGE = (
        9,
        "attackBoostEliteRankrewardMeleeEliteRankrewardRange",
    )
    RECUITMENT_SPEED_BOOST_ALL = 10, "recuitmentSpeedBoostAll"
    SPEED_BOOST_11 = 11, "SpeedBoost"
    FAME_BONUS_UNIT_ALIEN_BC_KINGSSPEERMAN = 12, "fameBonusUnitAlienBCKingsspeerman"
    FAME_BONUS_UNIT_ALIEN_BC_KINGSBOWMAN = 13, "fameBonusUnitAlienBCKingsbowman"
    FAME_BONUS_UNIT_ALIEN_BC_FLAMETHROWER = 14, "fameBonusUnitAlienBCFlamethrower"
    FAME_BONUS_UNIT_ALIEN_BC_ARROWTHROWER = 15, "fameBonusUnitAlienBCArrowthrower"
    FAME_BONUS_UNIT_ALIEN_BC_ELITE_FLAMETHROWER = 16, "fameBonusUnitAlienBCEliteFlamethrower"
    FAME_BONUS_UNIT_ALIEN_BC_ELITE_ARROWTHROWER = 17, "fameBonusUnitAlienBCEliteArrowthrower"
    BURNING_CHANCE_BONUS = 18, "burningChanceBonus"
    ATTACK_BOOST_YARD_PVP = 19, "attackBoostYardPVP"
