# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from enum import IntEnum


class Horse(IntEnum):
    """
    Travel booster ``wodID`` values from the ``horses`` table, the ``HBW`` movements send, named from the ``comment2``
    and ``comment1`` notes: the game names a horse only by its button's place in the travel dialog, the tooltip text
    ``horse<n>``.

    Client: ``HorseTravelboosterVO.parseXmlNode`` (bundle line 118814); ``ACastlePostActionDialog.calculateTooltip``
    (bundle line 27269)
    """

    HORSE_STABLE1 = 1001
    WARHORSE_STABLE1 = 1002
    COURSER_STABLE1 = 1003
    HORSE_STABLE2 = 1004
    WARHORSE_STABLE2 = 1005
    COURSER_STABLE2 = 1006
    HORSE_STABLE3 = 1007
    WARHORSE_STABLE3 = 1008
    COURSER_STABLE3 = 1009
    HORSE_FACTION_STABLE1 = 1021
    WARHORSE_FACTION_STABLE1 = 1022
    COURSER_FACTION_STABLE1 = 1023
    HORSE_FACTION_STABLE3 = 1024
    WARHORSE_FACTION_STABLE3 = 1025
    COURSER_FACTION_STABLE3 = 1026
    HORSE_FACTION_STABLE5 = 1027
    WARHORSE_FACTION_STABLE5 = 1028
    COURSER_FACTION_STABLE5 = 1029
    SHIP_HARBOR1 = 1030
    FAST_SHIP_HARBOR1 = 1031
    VERY_FAST_SHIP_HARBOR1 = 1032
    SHIP_HARBOR2 = 1033
    FAST_SHIP_HARBOR2 = 1034
    VERY_FAST_SHIP_HARBOR2 = 1035
    SHIP_HARBOR3 = 1036
    FAST_SHIP_HARBOR3 = 1037
    VERY_FAST_SHIP_HARBOR3 = 1038
    HORSE_FACTION_STABLE2 = 1039
    WARHORSE_FACTION_STABLE2 = 1040
    COURSER_FACTION_STABLE2 = 1041
    HORSE_FACTION_STABLE4 = 1042
    WARHORSE_FACTION_STABLE4 = 1043
    COURSER_FACTION_STABLE4 = 1044
