# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum


class LootBox(IntEnum):
    """
    Loot box ids from the ``lootBoxes`` table, named name and rarity.

    Client: ``LootBoxVO.parseXML`` (bundle line 112502)
    """

    _value_: int
    rarity: int
    """The ``rarity`` column."""

    def __new__(cls, value: int, rarity: int = 0) -> LootBox:
        member = int.__new__(cls, value)
        member._value_ = value
        member.rarity = rarity
        return member

    MYSTERY_BOX_BRONZE_R1 = 1, 1
    MYSTERY_BOX_BRONZE_R2 = 2, 2
    MYSTERY_BOX_BRONZE_R3 = 3, 3
    MYSTERY_BOX_BRONZE_R4 = 4, 4
    MYSTERY_BOX_SILVER_R1 = 5, 1
    MYSTERY_BOX_SILVER_R2 = 6, 2
    MYSTERY_BOX_SILVER_R3 = 7, 3
    MYSTERY_BOX_SILVER_R4 = 8, 4
    MYSTERY_BOX_GOLD_R1 = 9, 1
    MYSTERY_BOX_GOLD_R2 = 10, 2
    MYSTERY_BOX_GOLD_R3 = 11, 3
    MYSTERY_BOX_GOLD_R4 = 12, 4
    SUMMER_BOX2022_R1 = 13, 1
    SUMMER_BOX2022_R2 = 14, 2
    SUMMER_BOX2022_R3 = 15, 3
    SUMMER_BOX2022_R4 = 16, 4
    AUTUMN_BOX2022_R1 = 17, 1
    AUTUMN_BOX2022_R2 = 18, 2
    AUTUMN_BOX2022_R3 = 19, 3
    AUTUMN_BOX2022_R4 = 20, 4
    SALES_BOX2022_R1 = 21, 1
    SALES_BOX2022_R2 = 22, 2
    SALES_BOX2022_R3 = 23, 3
    SALES_BOX2022_R4 = 24, 4
    WINTER_BOX2022_R1 = 25, 1
    WINTER_BOX2022_R2 = 26, 2
    WINTER_BOX2022_R3 = 27, 3
    WINTER_BOX2022_R4 = 28, 4
    SPRING_BOX2023_R1 = 29, 1
    SPRING_BOX2023_R2 = 30, 2
    SPRING_BOX2023_R3 = 31, 3
    SPRING_BOX2023_R4 = 32, 4
    HO_L8_BOX_LITTLE_R1 = 33, 1
    HO_L8_BOX_BIG_R4 = 34, 4
    ARE_BOX_BRONZE_R1_35 = 35, 1
    ARE_BOX_SILVER_R1_36 = 36, 1
    ARE_BOX_GOLD_R1_37 = 37, 1
    ARE_BOX_BRONZE_PREMIUM_R1 = 38, 1
    ARE_BOX_SILVER_PREMIUM_R1 = 39, 1
    ARE_BOX_GOLD_PREMIUM_R1 = 40, 1
    ARE_BOX_BRONZE_R1_41 = 41, 1
    ARE_BOX_SILVER_R1_42 = 42, 1
    ARE_BOX_GOLD_R1_43 = 43, 1
    ARE_BOX_BRONZE_R1_44 = 44, 1
    ARE_BOX_SILVER_R1_45 = 45, 1
    ARE_BOX_GOLD_R1_46 = 46, 1
