# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from enum import IntEnum


class LootBoxType(IntEnum):
    """
    Loot box type ids from the ``lootBoxTypes`` table, named from ``lootBoxTheme``; keys count per type.

    Client: ``LootBoxTypeVO.parseXML`` (bundle line 58900)
    """

    MYSTERY_BOX = 1
