# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from enum import IntEnum


class MainQuest(IntEnum):
    """
    Main quest ids from the ``mainquests`` table, the quest book's chapters, named from the game's English title.

    Client: ``CastleQuestBookMainQuestListVO.parseListsFromParamObject`` (bundle line 52419); names from
    ``mainquest_<id>_title`` (bundle line 93386)
    """

    BRAVERY_AND_LUCK_IN_BATTLE = 1
    THE_DAMSEL_IN_DISTRESS = 2
    THE_LOVELY_BEATRICE = 3
    THE_DRAGON = 4
    TRUE_HAPPINESS = 5
    THE_EVERWINTER_GLACIER = 6
    ABDUCTION = 7
    THE_DRAGON_CULT = 8
