# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum

from empire_core.gamedata.data import default_game_data
from empire_core.gamedata.models import RaidBossDef


class RaidBoss(IntEnum):
    """
    Alliance raid boss ids from the ``raidBosses`` table.

    Client: ``AllianceRaidbossVO.parseXML`` (bundle line 113835)
    """

    _value_: int
    row_name: str
    """The row's name column."""

    def __new__(cls, value: int, row_name: str = "") -> RaidBoss:
        member = int.__new__(cls, value)
        member._value_ = value
        member.row_name = row_name
        return member

    @property
    def info(self) -> RaidBossDef | None:
        """This raid boss's row in the loaded game data, or None if it has none."""
        return default_game_data().raid_bosses.get(self)

    NECROMANCER = 1, "Necromancer"
    FUNGAL_SWARM = 2, "FungalSwarm"
    LEGENDARY_DRAGON = 3, "LegendaryDragon"
