# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from enum import IntEnum


class RaidBoss(IntEnum):
    """
    Alliance raid boss ids from the ``raidBosses`` table.

    Client: ``AllianceRaidbossVO.parseXML`` (bundle line 113835)
    """

    NECROMANCER = 1
    FUNGAL_SWARM = 2
    LEGENDARY_DRAGON = 3
