# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum

from empire_core.texts import text


class Title(IntEnum):
    """
    Title ids from the ``titles`` table, named from the game's English title.

    Client: ``TitleVO.parseXml`` (bundle line 62705); names from ``TitleVO.textID`` (bundle line 62756)
    """

    _value_: int
    title_system: str
    """Its title system, a ``TitleSystem`` value."""

    def __new__(cls, value: int, title_system: str = "") -> Title:
        member = int.__new__(cls, value)
        member._value_ = value
        member.title_system = title_system
        return member

    @property
    def text_id(self) -> str:
        """The text id of its name, ``playerTitle_<value>``."""
        return f"playerTitle_{self.value}"

    def display_name(self, lang: str = "en") -> str:
        """
        The game's name for it in ``lang``, the text ``playerTitle_<value>``.

        Fetches the language file on first use and caches it (:func:`empire_core.texts.text`); a text the file lacks, or
        a failed fetch, gives the text id.

        Client: ``TitleVO.textID`` (bundle line 62756)
        """
        return text(self.text_id, lang=lang)

    KNIGHT = 0, "FAME"
    CHEVALIER = 1, "FAME"
    BARONET = 2, "FAME"
    BARON = 3, "FAME"
    VISCOUNT = 4, "FAME"
    COUNT = 5, "FAME"
    COUNT_PALATINE = 6, "FAME"
    MARQUIS = 7, "FAME"
    VICE_DUKE = 8, "FAME"
    DUKE = 9, "FAME"
    GRAND_DUKE = 10, "FAME"
    ARCHDUKE = 11, "FAME"
    PRINCE = 12, "FAME"
    KING = 13, "FAME"
    THE_UNYIELDING = 14, "FAME"
    THE_GREAT = 15, "FAME"
    THE_CONQUEROR = 16, "FAME"
    THE_TERRIBLE = 17, "FAME"
    THE_MERCILESS = 18, "FAME"
    THE_VICTORIOUS = 19, "FAME"
    THE_STEEL_HEARTED = 20, "FAME"
    THE_RESOLUTE = 21, "FAME"
    THE_FURIOUS = 22, "FAME"
    THE_FEARLESS = 23, "FAME"
    THE_PROUD = 24, "FAME"
    THE_REMORSELESS = 25, "FAME"
    THE_FEARED = 26, "FAME"
    THE_INVINCIBLE = 27, "FAME"
    THE_NOBLE = 28, "FAME"
    THE_HONORABLE = 29, "FAME"
    THE_UNDAUNTED = 30, "FAME"
    THE_VENGEFUL = 31, "FAME"
    THE_VICIOUS = 32, "FAME"
    THE_RELENTLESS = 33, "FAME"
    STORM_LORD = 50, "ISLE"
    THE_VORACIOUS = 51, "ISLE"
    THE_HIVE_MASTER = 52, "ISLE"
    THE_WARRIOR_PRINCE = 53, "ISLE"
    THE_SHADOW_MASTER = 54, "ISLE"
    ACOLYTE = 100, "FACTION"
    PATRIOT = 101, "FACTION"
    OATH_KEEPER = 102, "FACTION"
    CAPTAIN = 103, "FACTION"
    STORMPIKE = 104, "FACTION"
    SHIELD_CRUSHER = 105, "FACTION"
    THE_FEARBRINGER = 106, "FACTION"
    THE_RAVAGER = 107, "FACTION"
    THE_WIDOWMAKER = 108, "FACTION"
    THE_OPPRESSOR = 109, "FACTION"
    THE_BLOODBLADE = 110, "FACTION"
    THE_DEATHCLAW = 111, "FACTION"
    GUARDIAN_OF_THE_SWORD = 112, "FACTION"
    WEAPON_MASTER = 113, "FACTION"
    RULER_OF_THE_BATTLE = 114, "FACTION"
    SUPREME_COMMANDER = 115, "FACTION"
    WAR_ADVISER = 116, "FACTION"
    CLAW_KING = 117, "FACTION"
