# Generated by scripts/generate_gamedata_ids.py from items 786.03; do not edit.

from __future__ import annotations

from enum import IntEnum

from empire_core.texts import text


class Tool(IntEnum):
    """
    Tool ``wodID`` values from the ``units`` table (rows with ``slotTypes``).

    Client: ``ToolUnitVO.parseXmlNode`` (bundle line 6538)
    """

    _value_: int
    level: int
    """Upgrade level; -1 when the row has none."""
    category: str
    """Attack or Defence; "0" when the row has none."""
    text_id: str
    """The text id the game names it by, which ``display_name`` reads."""

    def __new__(cls, value: int, level: int = 0, category: str = "", text_id: str = "") -> Tool:
        member = int.__new__(cls, value)
        member._value_ = value
        member.level = level
        member.category = category
        member.text_id = text_id
        return member

    def display_name(self, lang: str = "en") -> str:
        """
        The game's name for it in ``lang``, the text ``<type>_name``.

        Fetches the language file on first use and caches it (:func:`empire_core.texts.text`); a text the file lacks, or
        a failed fetch, gives the text id.

        Client: ``BasicUnitVO.getNameString`` (bundle line 19219)
        """
        return text(self.text_id, lang=lang)

    NOMAD_TABLET_BOOST = 1, -1, "Attack", "nomadtabletboost_name"
    ALMONDSHIELD = 2, -1, "Attack", "almondshield_name"
    FENRISWOLFHORN = 3, -1, "Attack", "fenriswolfhorn_name"
    TONNELON = 4, -1, "Attack", "tonnelon_name"
    BERIMOND_POINT_BOOST = 16, -1, "Attack", "berimondpointboost_name"
    ELITE_BERIMOND_POINT_BOOST = 17, -1, "Attack", "eliteberimondpointboost_name"
    CHAMPION_BANNER = 24, -1, "Attack", "championbanner_name"
    SAMURAI_ANTI_RAM = 25, -1, "Attack", "samuraiantiram_name"
    SAMURAI_ANTI_LADDER = 26, -1, "Attack", "samuraiantiladder_name"
    SAMURAI_ANTI_SHIELD = 27, -1, "Attack", "samuraiantishield_name"
    SAMURAI_BANNER = 28, -1, "Attack", "samuraibanner_name"
    SAMURAI_BALLISTA = 29, -1, "Attack", "samuraiballista_name"
    SAMURAI_POINT_BOOST = 30, -1, "Attack", "samuraipointboost_name"
    ELITE_SAMURAI_POINT_BOOST = 31, -1, "Attack", "elitesamuraipointboost_name"
    SAMURAI_BULWARK = 32, -1, "Defence", "samuraibulwark_name"
    SAMURAI_CHALKBOMB = 33, -1, "Defence", "samuraichalkbomb_name"
    HALLOWEEN_ATTACK_TOOL = 44, -1, "Attack", "halloweenattacktool_name"
    HALLOWEEN_DEFENSE_TOOL = 45, -1, "Defence", "halloweendefensetool_name"
    WINTER_RAM = 53, -1, "Attack", "winterram_name"
    WINTER_LADDER = 54, -1, "Attack", "winterladder_name"
    WINTER_SHIELD = 55, -1, "Attack", "wintershield_name"
    LIGHT_STONE = 56, -1, "Attack", "lightstone_name"
    HEAVY_STONE = 57, -1, "Attack", "heavystone_name"
    BANNER_USA_60 = 60, -1, "Attack", "bannerusa_name"
    WINTER_XP_TOOL = 61, -1, "Attack", "winterxptool_name"
    NOMAD_COIN_BOOST = 62, -1, "Attack", "nomadcoinboost_name"
    SAMURAI_COIN_BOOST = 63, -1, "Attack", "samuraicoinboost_name"
    WINTER_ELITE_BANNER = 64, -1, "Attack", "winterelitebanner_name"
    ALLIANCE_CITY_COIN_BOOST = 65, -1, "Attack", "alliancecitycoinboost_name"
    PREMIUM_ALLIANCE_CITY_COIN_BOOST = 66, -1, "Attack", "premiumalliancecitycoinboost_name"
    PREMIUM_COIN_BOOST = 67, -1, "Attack", "premiumcoinboost_name"
    UNDERWORLD_LADDER = 69, -1, "Attack", "underworldladder_name"
    UNDERWORLD_SHIELDS = 70, -1, "Attack", "underworldshields_name"
    UNDERWORLD_BANNER = 71, -1, "Attack", "underworldbanner_name"
    UNDERWORLD_RAM = 72, -1, "Attack", "underworldram_name"
    ELITE_COIN_BOOST = 73, -1, "Attack", "elitecoinboost_name"
    ELITE_BANNER = 77, -1, "Attack", "elitebanner_name"
    UNDERWORLD_BALLISTA = 80, -1, "Attack", "underworldballista_name"
    BERIMOND_INVASION_REPUTATION_BOOST = 81, -1, "Attack", "berimondinvasionreputationboost_name"
    ELITE_BERIMOND_INVASION_REPUTATION_BOOST = 82, -1, "Attack", "eliteberimondinvasionreputationboost_name"
    SPRING_RAM = 87, -1, "Attack", "springram_name"
    SPRING_LADDER = 88, -1, "Attack", "springladder_name"
    SPRING_SHIELD = 89, -1, "Attack", "springshield_name"
    SPRING_XP_TOOL = 90, -1, "Attack", "springxptool_name"
    ELITE_XP_TOOL = 91, -1, "Attack", "elitexptool_name"
    ELITE_ALLIANCE_CITY_COIN_BOOST = 94, -1, "Attack", "elitealliancecitycoinboost_name"
    ALLIANCE_CITY_TOKEN_BOOST = 95, -1, "Attack", "alliancecitytokenboost_name"
    PREMIUM_ALLIANCE_CITY_TOKEN_BOOST = 96, -1, "Attack", "premiumalliancecitytokenboost_name"
    ELITE_ALLIANCE_CITY_TOKEN_BOOST = 97, -1, "Attack", "elitealliancecitytokenboost_name"
    ELITE_BODKINHEAD = 104, -1, "Defence", "elitebodkinhead_name"
    ELITE_CHALKBOMB = 105, -1, "Defence", "elitechalkbomb_name"
    RAGE_BOOST_106 = 106, -1, "Attack", "rageboost_name"
    NOMAD_RAGE_TABLET_BOOST = 107, -1, "Attack", "nomadragetabletboost_name"
    NOMAD_DEFENSE_KEEP = 108, -1, "Defence", "nomaddefensekeep_name"
    NOMAD_ELITE_DEFENSE_WALL = 109, -1, "Defence", "nomadelitedefensewall_name"
    NOMAD_ELITE_DEFENSE_RANGED = 110, -1, "Defence", "nomadelitedefenseranged_name"
    NOMAD_ELITE_DEFENSE_GATE = 111, -1, "Defence", "nomadelitedefensegate_name"
    NOMAD_ELITE_DEFENSE_MOAT = 112, -1, "Defence", "nomadelitedefensemoat_name"
    ELITE_COMBO_RAM_113 = 113, -1, "Attack", "elitecomboram_name"
    ELITE_TONNELON_114 = 114, -1, "Attack", "elitetonnelon_name"
    ELITE_COMBO_BUNDLES = 115, -1, "Attack", "elitecombobundles_name"
    ELITE_ALMONDSHIELD = 116, -1, "Attack", "elitealmondshield_name"
    GRIMS_SHIELD = 121, -1, "Attack", "grimsshield_name"
    GRIMS_LADDER = 122, -1, "Attack", "grimsladder_name"
    GRIMS_RAM = 123, -1, "Attack", "grimsram_name"
    GRIMS_CROSSING = 124, -1, "Attack", "grimscrossing_name"
    FLEET_SHIELD = 125, -1, "Attack", "fleetshield_name"
    FESTIVE_RAM = 128, -1, "Attack", "festiveram_name"
    CANDY_CANE_LADDER = 129, -1, "Attack", "candycaneladder_name"
    YULE_SHIELD = 130, -1, "Attack", "yuleshield_name"
    BAUBLE_MOAT = 131, -1, "Attack", "baublemoat_name"
    SHAPESHIFTER_ELITERAM = 137, -1, "Attack", "shapeshiftereliteram_name"
    SHAPESHIFTER_ELITELADDER = 138, -1, "Attack", "shapeshiftereliteladder_name"
    SHAPESHIFTER_ELITEBUNDLES = 139, -1, "Attack", "shapeshifterelitebundles_name"
    SHAPESHIFTER_ELITESHIELDS = 140, -1, "Attack", "shapeshiftereliteshields_name"
    ELITE_NOMAD_COMBO_RAM_141 = 141, -1, "Attack", "elitenomadcomboram_name"
    ELITE_NOMAD_COMBO_LADDER_142 = 142, -1, "Attack", "elitenomadcomboladder_name"
    ELITE_NOMAD_COMBO_SHIELD_143 = 143, -1, "Attack", "elitenomadcomboshield_name"
    ROYAL_BANNER = 152, -1, "Attack", "royalbanner_name"
    KINGS_BANNER = 153, -1, "Attack", "kingsbanner_name"
    ROYAL_RAM = 154, -1, "Attack", "royalram_name"
    KINGS_RAM = 155, -1, "Attack", "kingsram_name"
    ROYAL_LADDER = 156, -1, "Attack", "royalladder_name"
    KINGS_LADDER = 157, -1, "Attack", "kingsladder_name"
    ROYAL_BUNDLES = 158, -1, "Attack", "royalbundles_name"
    KINGS_BUNDLES = 159, -1, "Attack", "kingsbundles_name"
    ROYAL_SHIELDS = 160, -1, "Attack", "royalshields_name"
    KINGS_SHIELDS = 161, -1, "Attack", "kingsshields_name"
    SILVER_KHAN_CHEST = 162, -1, "Attack", "silverkhanchest_name"
    GOLD_KHAN_CHEST = 163, -1, "Attack", "goldkhanchest_name"
    ROYAL_KHAN_CHEST = 164, -1, "Attack", "royalkhanchest_name"
    CASE_OF_THE_SHOGUN = 165, -1, "Attack", "caseoftheshogun_name"
    CHEST_OF_THE_SHOGUN = 166, -1, "Attack", "chestoftheshogun_name"
    IMPROVED_FIRERAM = 167, -1, "Attack", "improvedfireram_name"
    IMPROVED_TREE_LADDER = 168, -1, "Attack", "improvedtreeladder_name"
    IMPROVED_ROLLING_SHIELD = 169, -1, "Attack", "improvedrollingshield_name"
    RAM_OF_THE_SHOGUN_170 = 170, -1, "Attack", "ramoftheshogun_name"
    LADDER_OF_THE_SHOGUN_171 = 171, -1, "Attack", "ladderoftheshogun_name"
    SHIELD_OF_THE_SHOGUN_172 = 172, -1, "Attack", "shieldoftheshogun_name"
    LOW_BERIMOND_POINT_BOOST = 178, -1, "Attack", "lowberimondpointboost_name"
    MAYA_MAT = 179, -1, "Defence", "mayamat_name"
    MAYA_ROCKS = 180, -1, "Defence", "mayarocks_name"
    MAYA_STAKES = 181, -1, "Defence", "mayastakes_name"
    MAYA_ARROW = 182, -1, "Defence", "mayaarrow_name"
    VISCOUNT_BANNER = 239, -1, "Attack", "viscountbanner_name"
    EMPERORS_BANNER = 240, -1, "Attack", "emperorsbanner_name"
    VISCOUNT_BERIMOND_POINT_BOOST = 241, -1, "Attack", "viscountberimondpointboost_name"
    EMPEROR_BERIMOND_POINT_BOOST = 242, -1, "Attack", "emperorberimondpointboost_name"
    VISCOUNT_KHAN_CHEST = 243, -1, "Attack", "viscountkhanchest_name"
    EMPEROR_KHAN_CHEST = 244, -1, "Attack", "emperorkhanchest_name"
    SCEAT_ATT_GATE_DEF_RANGE_L1 = 245, 1, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L2 = 246, 2, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L3 = 247, 3, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L4 = 248, 4, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L5 = 249, 5, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L6 = 250, 6, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L7 = 251, 7, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L8 = 252, 8, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L9 = 253, 9, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L10 = 254, 10, "Attack", "sceatattgatedefrange_name"
    SCEAT_ATT_GATE_DEF_RANGE_L11 = 255, 11, "Attack", "sceatattgatedefrange_name"
    SCEAT_FAME_SHIELD_L1 = 256, 1, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L2 = 257, 2, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L3 = 258, 3, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L4 = 259, 4, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L5 = 260, 5, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L6 = 261, 6, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L7 = 262, 7, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L8 = 263, 8, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L9 = 264, 9, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L10 = 265, 10, "Attack", "sceatfameshield_name"
    SCEAT_FAME_SHIELD_L11 = 266, 11, "Attack", "sceatfameshield_name"
    SCEAT_ATT_WALL_MELEE_L1 = 267, 1, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L2 = 268, 2, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L3 = 269, 3, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L4 = 270, 4, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L5 = 271, 5, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L6 = 272, 6, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L7 = 273, 7, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L8 = 274, 8, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L9 = 275, 9, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_WALL_MELEE_L10 = 276, 10, "Attack", "sceatattwallmelee_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L1 = 278, 1, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L2 = 279, 2, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L3 = 280, 3, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L4 = 281, 4, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L5 = 282, 5, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L6 = 283, 6, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L7 = 284, 7, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L8 = 285, 8, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L9 = 286, 9, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_MOAT_ATT_RANGE_L10 = 287, 10, "Attack", "sceatattmoatattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L1 = 289, 1, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L2 = 290, 2, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L3 = 291, 3, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L4 = 292, 4, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L5 = 293, 5, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L6 = 294, 6, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L7 = 295, 7, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L8 = 296, 8, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L9 = 297, 9, "Attack", "sceatattwallattrange_name"
    SCEAT_ATT_WALL_ATT_RANGE_L10 = 298, 10, "Attack", "sceatattwallattrange_name"
    SCEAT_DEF_GATE_RANGE_L1 = 300, 1, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L2 = 301, 2, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L3 = 302, 3, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L4 = 303, 4, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L5 = 304, 5, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L6 = 305, 6, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L7 = 306, 7, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L8 = 307, 8, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L9 = 310, 9, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L10 = 313, 10, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_GATE_RANGE_L11 = 314, 11, "Defence", "sceatdefgaterange_name"
    SCEAT_DEF_WALL_MOAT_L1 = 315, 1, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L2 = 316, 2, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L3 = 317, 3, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L4 = 318, 4, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L5 = 319, 5, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L6 = 320, 6, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L7 = 321, 7, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L8 = 322, 8, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L9 = 323, 9, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L10 = 324, 10, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_MOAT_L11 = 325, 11, "Defence", "sceatdefwallmoat_name"
    SCEAT_DEF_WALL_RANGE_L1 = 326, 1, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L2 = 327, 2, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L3 = 328, 3, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L4 = 329, 4, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L5 = 330, 5, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L6 = 331, 6, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L7 = 332, 7, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L8 = 333, 8, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L9 = 334, 9, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_WALL_RANGE_L10 = 335, 10, "Defence", "sceatdefwallrange_name"
    SCEAT_DEF_MELEE_MOAT_L1 = 337, 1, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L2 = 338, 2, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L3 = 339, 3, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L4 = 340, 4, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L5 = 341, 5, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L6 = 342, 6, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L7 = 343, 7, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L8 = 344, 8, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L9 = 345, 9, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_MELEE_MOAT_L10 = 346, 10, "Defence", "sceatdefmeleemoat_name"
    SCEAT_DEF_WALL_MELEE_L1 = 348, 1, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L2 = 349, 2, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L3 = 350, 3, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L4 = 351, 4, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L5 = 352, 5, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L6 = 353, 6, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L7 = 354, 7, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L8 = 355, 8, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L9 = 356, 9, "Defence", "sceatdefwallmelee_name"
    SCEAT_DEF_WALL_MELEE_L10 = 357, 10, "Defence", "sceatdefwallmelee_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L1 = 359, 1, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L2 = 360, 2, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L3 = 361, 3, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L4 = 362, 4, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L5 = 363, 5, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L6 = 364, 6, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L7 = 365, 7, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L8 = 366, 8, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L9 = 367, 9, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_MELEE_DEF_L10 = 368, 10, "Attack", "sceatsuppkillmeleedef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L1 = 370, 1, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L2 = 371, 2, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L3 = 372, 3, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L4 = 373, 4, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L5 = 374, 5, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L6 = 375, 6, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L7 = 376, 7, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L8 = 377, 8, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L9 = 378, 9, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_KILL_RANGED_DEF_L10 = 379, 10, "Attack", "sceatsuppkillrangeddef_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L1 = 381, 1, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L2 = 382, 2, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L3 = 383, 3, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L4 = 384, 4, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L5 = 385, 5, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L6 = 386, 6, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L7 = 387, 7, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L8 = 388, 8, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L9 = 389, 9, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_ATTACK_POWER_L10 = 390, 10, "Attack", "sceatsuppattattackpower_name"
    SCEAT_SUPP_ATT_POWER_YARD_L1 = 391, 1, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L2 = 392, 2, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L3 = 393, 3, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L4 = 394, 4, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L5 = 395, 5, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L6 = 396, 6, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L7 = 397, 7, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L8 = 398, 8, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L9 = 399, 9, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_POWER_YARD_L10 = 400, 10, "Attack", "sceatsuppattpoweryard_name"
    SCEAT_SUPP_ATT_WAVES_L1 = 401, 1, "Attack", "sceatsuppattwaves_name"
    SCEAT_SUPP_ATT_WAVES_L2 = 402, 2, "Attack", "sceatsuppattwaves_name"
    SCEAT_SUPP_ATT_WAVES_L3 = 403, 3, "Attack", "sceatsuppattwaves_name"
    LARGE_KHAN_TABLET_CHEST = 404, -1, "Attack", "largekhantabletchest_name"
    HUGE_KHAN_TABLET_CHEST = 405, -1, "Attack", "hugekhantabletchest_name"
    LARGE_SAMURAI_TOKEN_CHEST = 406, -1, "Attack", "largesamuraitokenchest_name"
    HUGE_SAMURAI_TOKEN_CHEST = 407, -1, "Attack", "hugesamuraitokenchest_name"
    BANNER_USA_408 = 408, -1, "Attack", "bannerusa_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L1 = 421, 1, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L2 = 422, 2, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L3 = 423, 3, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L4 = 424, 4, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L5 = 425, 5, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L6 = 426, 6, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L7 = 427, 7, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L8 = 428, 8, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L9 = 429, 9, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_KILL_ATTACKERS_L10 = 430, 10, "Defence", "sceatsuppdefkillattackers_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L1 = 431, 1, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L2 = 432, 2, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L3 = 433, 3, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L4 = 434, 4, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L5 = 435, 5, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L6 = 436, 6, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L7 = 437, 7, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L8 = 438, 8, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L9 = 439, 9, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_DEFENSE_POWER_YARD_L10 = 440, 10, "Defence", "sceatsuppdefdefensepoweryard_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L1 = 441, 1, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L2 = 442, 2, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L3 = 443, 3, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L4 = 444, 4, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L5 = 445, 5, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L6 = 446, 6, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L7 = 447, 7, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L8 = 448, 8, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L9 = 449, 9, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_WALL_AMOUNT_L10 = 450, 10, "Defence", "sceatsuppdefwallamount_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L1 = 451, 1, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L2 = 452, 2, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L3 = 453, 3, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L4 = 454, 4, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L5 = 455, 5, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L6 = 456, 6, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L7 = 457, 7, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L8 = 458, 8, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L9 = 459, 9, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_MELEE_ATTACKERS_L10 = 460, 10, "Defence", "sceatsuppdefkillmeleeattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L1 = 462, 1, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L2 = 463, 2, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L3 = 464, 3, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L4 = 465, 4, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L5 = 466, 5, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L6 = 467, 6, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L7 = 468, 7, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L8 = 469, 8, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L9 = 470, 9, "Defence", "sceatsuppdefkillrangedattackers_name"
    SCEAT_SUPP_DEF_KILL_RANGED_ATTACKERS_L10 = 471, 10, "Defence", "sceatsuppdefkillrangedattackers_name"
    HIGH_QUEENS_BANNER = 474, -1, "Attack", "highqueensbanner_name"
    HIGH_KINGS_BANNER = 475, -1, "Attack", "highkingsbanner_name"
    SUPREME_MONARCHS_BANNER = 476, -1, "Attack", "suprememonarchsbanner_name"
    GIANT_NOMAD_TABLET_CHEST = 490, -1, "Attack", "giantnomadtabletchest_name"
    ENORMOUS_NOMAD_TABLET_CHEST = 491, -1, "Attack", "enormousnomadtabletchest_name"
    COLOSSAL_NOMAD_TABLET_CHEST = 492, -1, "Attack", "colossalnomadtabletchest_name"
    GIANT_SAMURAI_TOKEN_CHEST = 510, -1, "Attack", "giantsamuraitokenchest_name"
    ENORMOUS_SAMURAI_TOKEN_CHEST = 511, -1, "Attack", "enormoussamuraitokenchest_name"
    COLOSSAL_SAMURAI_TOKEN_CHEST = 512, -1, "Attack", "colossalsamuraitokenchest_name"
    RAM_OF_THE_SHOGUN_557 = 557, -1, "Attack", "ramoftheshogun_name"
    SHIELD_OF_THE_SHOGUN_558 = 558, -1, "Attack", "shieldoftheshogun_name"
    LADDER_OF_THE_SHOGUN_559 = 559, -1, "Attack", "ladderoftheshogun_name"
    ELITE_NOMAD_COMBO_RAM_560 = 560, -1, "Attack", "elitenomadcomboram_name"
    ELITE_NOMAD_COMBO_LADDER_561 = 561, -1, "Attack", "elitenomadcomboladder_name"
    ELITE_NOMAD_COMBO_SHIELD_562 = 562, -1, "Attack", "elitenomadcomboshield_name"
    RAGE_BOOST_563 = 563, -1, "Attack", "rageboost_name"
    ELITE_COMBO_RAM_564 = 564, -1, "Attack", "elitecomboram_name"
    ELITE_TONNELON_565 = 565, -1, "Attack", "elitetonnelon_name"
    ALIEN_INVASION_ANTI_SHIELDS_566 = 566, -1, "Attack", "alieninvasionantishields_name"
    SCEAT_SUPP_ATT_WAVES_L4 = 567, 4, "Attack", "sceatsuppattwaves_name"
    ARE_WALL_DEBUFF_NORMAL60 = 568, -1, "Attack", "arewalldebuffnormal60_name"
    ARE_WALL_DEBUFF_PREMIUM250 = 569, -1, "Attack", "arewalldebuffpremium250_name"
    ARE_GATE_DEBUFF_NORMAL60 = 570, -1, "Attack", "aregatedebuffnormal60_name"
    ARE_GATE_DEBUFF_PREMIUM250 = 571, -1, "Attack", "aregatedebuffpremium250_name"
    ARE_WALL_DEBUFF_CURRENCY_BOOST_NORMAL = 572, -1, "Attack", "arewalldebuffcurrencyboostnormal_name"
    ARE_WALL_DEBUFF_CURRENCY_BOOST_PREMIUM = 573, -1, "Attack", "arewalldebuffcurrencyboostpremium_name"
    ARE_GATE_DEBUFF_CURRENCY_BOOST_NORMAL = 574, -1, "Attack", "aregatedebuffcurrencyboostnormal_name"
    ARE_GATE_DEBUFF_CURRENCY_BOOST_PREMIUM = 575, -1, "Attack", "aregatedebuffcurrencyboostpremium_name"
    ARE_EVENT_CURRENCY_BOOST_WEAK = 576, -1, "Attack", "areeventcurrencyboostweak_name"
    ARE_EVENT_CURRENCY_BOOST_MEDIUM = 577, -1, "Attack", "areeventcurrencyboostmedium_name"
    ARE_EVENT_CURRENCY_BOOST_STRONG = 578, -1, "Attack", "areeventcurrencybooststrong_name"
    ARE_INFECTION_RATE_BOOST_WEAK = 579, -1, "Attack", "areinfectionrateboostweak_name"
    ARE_INFECTION_RATE_BOOST_NORMAL = 580, -1, "Attack", "areinfectionrateboostnormal_name"
    ARE_INFECTION_RATE_BOOST_PREMIUM = 581, -1, "Attack", "areinfectionrateboostpremium_name"
    ARE_WALL_DEBUFF_NORMAL80 = 583, -1, "Attack", "arewalldebuffnormal80_name"
    ARE_WALL_DEBUFF_NORMAL125 = 584, -1, "Attack", "arewalldebuffnormal125_name"
    ARE_WALL_DEBUFF_NORMAL200 = 585, -1, "Attack", "arewalldebuffnormal200_name"
    ARE_WALL_DEBUFF_PREMIUM340 = 586, -1, "Attack", "arewalldebuffpremium340_name"
    ARE_WALL_DEBUFF_PREMIUM500 = 587, -1, "Attack", "arewalldebuffpremium500_name"
    ARE_GATE_DEBUFF_NORMAL80 = 588, -1, "Attack", "aregatedebuffnormal80_name"
    ARE_GATE_DEBUFF_NORMAL125 = 589, -1, "Attack", "aregatedebuffnormal125_name"
    ARE_GATE_DEBUFF_NORMAL200 = 590, -1, "Attack", "aregatedebuffnormal200_name"
    ARE_GATE_DEBUFF_PREMIUM340 = 591, -1, "Attack", "aregatedebuffpremium340_name"
    ARE_GATE_DEBUFF_PREMIUM500 = 592, -1, "Attack", "aregatedebuffpremium500_name"
    RAM = 611, -1, "Attack", "ram_name"
    LADDER = 614, -1, "Attack", "ladder_name"
    BUNDLES = 617, -1, "Attack", "bundles_name"
    SHIELDS = 620, -1, "Attack", "shields_name"
    ELITEMAT = 622, -1, "Defence", "elitemat_name"
    ISLAND_LADDER = 623, -1, "Attack", "islandladder_name"
    ELITEBRAZIER = 624, -1, "Defence", "elitebrazier_name"
    ELITESTAKES = 625, -1, "Defence", "elitestakes_name"
    GATEHARDENING = 626, -1, "Defence", "gatehardening_name"
    ELITEOILSMELTER = 627, -1, "Defence", "eliteoilsmelter_name"
    BRAZIER = 629, -1, "Defence", "brazier_name"
    DOLLMELEE = 632, -1, "Defence", "dollmelee_name"
    DOLLRANGE = 633, -1, "Defence", "dollrange_name"
    STAKES = 634, -1, "Defence", "stakes_name"
    PREMIUMSHIELDS = 635, -1, "Attack", "premiumshields_name"
    OILSMELTER = 637, -1, "Defence", "oilsmelter_name"
    ISLAND_BANNER = 638, -1, "Attack", "islandbanner_name"
    PREMIUMDOLLRANGE = 639, -1, "Defence", "premiumdollrange_name"
    SIEGETOWER = 640, -1, "Attack", "siegetower_name"
    PREMIUMRAM = 641, -1, "Attack", "premiumram_name"
    PREMIUMBUNDLES = 642, -1, "Attack", "premiumbundles_name"
    ISLAND_SHIELDS = 643, -1, "Attack", "islandshields_name"
    MAT = 644, -1, "Defence", "mat_name"
    BULWARK = 645, -1, "Defence", "bulwark_name"
    PREMIUMSTAKES = 646, -1, "Defence", "premiumstakes_name"
    PREMIUMOILSMELTER = 647, -1, "Defence", "premiumoilsmelter_name"
    ELITERAM = 648, -1, "Attack", "eliteram_name"
    ELITELADDER = 649, -1, "Attack", "eliteladder_name"
    ELITEBUNDLES = 650, -1, "Attack", "elitebundles_name"
    ELITESHIELDS = 651, -1, "Attack", "eliteshields_name"
    BAG = 653, -1, "Attack", "bag_name"
    BARROW = 654, -1, "Attack", "barrow_name"
    FLAG = 660, -1, "Attack", "flag_name"
    BANNER = 661, -1, "Attack", "banner_name"
    TOOLS = 666, -1, "Defence", "tools_name"
    ISLAND_BALLISTA = 669, -1, "Attack", "islandballista_name"
    CHALKBOMB = 730, -1, "Defence", "chalkbomb_name"
    BODKINHEAD = 731, -1, "Defence", "bodkinhead_name"
    TORTOISE = 732, -1, "Attack", "tortoise_name"
    GRAPPLINGHOOK = 733, -1, "Attack", "grapplinghook_name"
    HORSETAILBANNER = 734, -1, "Attack", "horsetailbanner_name"
    PEASANTDOLL = 735, -1, "Attack", "peasantdoll_name"
    YAKPACKANIMAL = 736, -1, "Attack", "yakpackanimal_name"
    WARHORN = 737, -1, "Attack", "warhorn_name"
    FIRERAM = 738, -1, "Attack", "fireram_name"
    ROLLINGSHIELDS = 739, -1, "Attack", "rollingshields_name"
    TRUNKLADDER = 740, -1, "Attack", "trunkladder_name"
    TORCHES = 741, -1, "Attack", "torches_name"
    POISONARROW = 742, -1, "Attack", "poisonarrow_name"
    XP_TOOL = 745, -1, "Attack", "xptool_name"
    THORNKING_LADDER = 755, -1, "Attack", "thornkingladder_name"
    THORNKING_SHIELDS = 756, -1, "Attack", "thornkingshields_name"
    THORNKING_BANNER = 757, -1, "Attack", "thornkingbanner_name"
    THORNKING_BALLISTA = 758, -1, "Attack", "thornkingballista_name"
    SEAQUEEN_LADDER = 761, -1, "Attack", "seaqueenladder_name"
    SEAQUEEN_SHIELDS = 762, -1, "Attack", "seaqueenshields_name"
    SEAQUEEN_BANNER = 763, -1, "Attack", "seaqueenbanner_name"
    SEAQUEEN_BALLISTA = 764, -1, "Attack", "seaqueenballista_name"
    ALIEN_INVASION_ANTI_RAM = 770, -1, "Attack", "alieninvasionantiram_name"
    ALIEN_INVASION_ANTI_LADDER = 771, -1, "Attack", "alieninvasionantiladder_name"
    ALIEN_INVASION_ANTI_BUNDLE = 772, -1, "Attack", "alieninvasionantibundle_name"
    ALIEN_INVASION_ANTI_SHIELDS_773 = 773, -1, "Attack", "alieninvasionantishields_name"
    ALIEN_INVASION_ANTI_BANNER = 774, -1, "Attack", "alieninvasionantibanner_name"
    BERIMOND_ANTI_RAM = 775, -1, "Attack", "berimondantiram_name"
    BERIMOND_ANTI_LADDER = 776, -1, "Attack", "berimondantiladder_name"
    BERIMOND_ANTI_BUNDLE = 777, -1, "Attack", "berimondantibundle_name"
    BERIMOND_ANTI_SHIELDS = 778, -1, "Attack", "berimondantishields_name"
    BERIMOND_ANTI_BANNER = 779, -1, "Attack", "berimondantibanner_name"
    BERIMOND_ANTI_BOOST = 780, -1, "Attack", "berimondantiboost_name"
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_LEFT_WEAK = (
        789,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaseleftweak_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_FRONT_WEAK = (
        790,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreasefrontweak_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_RIGHT_WEAK = (
        791,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaserightweak_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_ALL_WEAK = (
        792,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaseallweak_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_LEFT_NORMAL = (
        793,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaseleftnormal_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_FRONT_NORMAL = (
        794,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreasefrontnormal_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_RIGHT_NORMAL = (
        795,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaserightnormal_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_ALL_NORMAL = (
        796,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaseallnormal_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_LEFT_STRONG = (
        797,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaseleftstrong_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_FRONT_STRONG = (
        798,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreasefrontstrong_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_RIGHT_STRONG = (
        799,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaserightstrong_name",
    )
    ARE_LEGENDARY_DRAGON_WALL_DELAY_INCREASE_ALL_STRONG = (
        800,
        -1,
        "Attack",
        "arelegendarydragonwalldelayincreaseallstrong_name",
    )
    ARE_LEGENDARY_DRAGON_EGG_KILLING_TOOL_WEAK = 801, -1, "Attack", "arelegendarydragoneggkillingtoolweak_name"
    ARE_LEGENDARY_DRAGON_EGG_KILLING_TOOL_MEDIUM = 802, -1, "Attack", "arelegendarydragoneggkillingtoolmedium_name"
    ARE_LEGENDARY_DRAGON_EGG_KILLING_TOOL_STRONG = 803, -1, "Attack", "arelegendarydragoneggkillingtoolstrong_name"
    ARE_LEGENDARY_DRAGON_HATCHLING_KILLING_TOOL_WEAK = (
        804,
        -1,
        "Attack",
        "arelegendarydragonhatchlingkillingtoolweak_name",
    )
    ARE_LEGENDARY_DRAGON_HATCHLING_KILLING_TOOL_MEDIUM = (
        805,
        -1,
        "Attack",
        "arelegendarydragonhatchlingkillingtoolmedium_name",
    )
    ARE_LEGENDARY_DRAGON_HATCHLING_KILLING_TOOL_STRONG = (
        806,
        -1,
        "Attack",
        "arelegendarydragonhatchlingkillingtoolstrong_name",
    )
    ARE_LEGENDARY_DRAGON_WEAKENING_TOOL_MELEE_WEAK = 807, -1, "Attack", "arelegendarydragonweakeningtoolmeleeweak_name"
    ARE_LEGENDARY_DRAGON_WEAKENING_TOOL_MELEE_MEDIUM = (
        808,
        -1,
        "Attack",
        "arelegendarydragonweakeningtoolmeleemedium_name",
    )
    ARE_LEGENDARY_DRAGON_WEAKENING_TOOL_MELEE_STRONG = (
        809,
        -1,
        "Attack",
        "arelegendarydragonweakeningtoolmeleestrong_name",
    )
    ARE_LEGENDARY_DRAGON_WEAKENING_TOOL_RANGED_WEAK = (
        810,
        -1,
        "Attack",
        "arelegendarydragonweakeningtoolrangedweak_name",
    )
    ARE_LEGENDARY_DRAGON_WEAKENING_TOOL_RANGED_MEDIUM = (
        811,
        -1,
        "Attack",
        "arelegendarydragonweakeningtoolrangedmedium_name",
    )
    ARE_LEGENDARY_DRAGON_WEAKENING_TOOL_RANGED_STRONG = (
        812,
        -1,
        "Attack",
        "arelegendarydragonweakeningtoolrangedstrong_name",
    )
    SAMURAI_CHALKBOMB_L1 = 840, 1, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L2 = 841, 2, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L3 = 842, 3, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L4 = 843, 4, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L5 = 844, 5, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L6 = 845, 6, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L7 = 846, 7, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L8 = 847, 8, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L9 = 848, 9, "Defence", "samuraichalkbomb_name"
    SAMURAI_CHALKBOMB_L10 = 849, 10, "Defence", "samuraichalkbomb_name"
    SAMURAI_BULWARK_L1 = 850, 1, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L2 = 851, 2, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L3 = 852, 3, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L4 = 853, 4, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L5 = 854, 5, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L6 = 855, 6, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L7 = 856, 7, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L8 = 857, 8, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L9 = 858, 9, "Defence", "samuraibulwark_name"
    SAMURAI_BULWARK_L10 = 859, 10, "Defence", "samuraibulwark_name"
    SAMURAI_BALLISTA_L1 = 880, 1, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L2 = 881, 2, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L3 = 882, 3, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L4 = 883, 4, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L5 = 884, 5, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L6 = 885, 6, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L7 = 886, 7, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L8 = 887, 8, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L9 = 888, 9, "Attack", "samuraiballista_name"
    SAMURAI_BALLISTA_L10 = 889, 10, "Attack", "samuraiballista_name"
    SAMURAI_BANNER_L1 = 890, 1, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L2 = 891, 2, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L3 = 892, 3, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L4 = 893, 4, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L5 = 894, 5, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L6 = 895, 6, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L7 = 896, 7, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L8 = 897, 8, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L9 = 898, 9, "Attack", "samuraibanner_name"
    SAMURAI_BANNER_L10 = 899, 10, "Attack", "samuraibanner_name"
    CHALKBOMB_L1 = 920, 1, "Defence", "chalkbomb_name"
    CHALKBOMB_L2 = 921, 2, "Defence", "chalkbomb_name"
    CHALKBOMB_L3 = 922, 3, "Defence", "chalkbomb_name"
    CHALKBOMB_L4 = 923, 4, "Defence", "chalkbomb_name"
    CHALKBOMB_L5 = 924, 5, "Defence", "chalkbomb_name"
    CHALKBOMB_L6 = 925, 6, "Defence", "chalkbomb_name"
    CHALKBOMB_L7 = 926, 7, "Defence", "chalkbomb_name"
    CHALKBOMB_L8 = 927, 8, "Defence", "chalkbomb_name"
    CHALKBOMB_L9 = 928, 9, "Defence", "chalkbomb_name"
    CHALKBOMB_L10 = 929, 10, "Defence", "chalkbomb_name"
    BODKINHEAD_L1 = 930, 1, "Defence", "bodkinhead_name"
    BODKINHEAD_L2 = 931, 2, "Defence", "bodkinhead_name"
    BODKINHEAD_L3 = 932, 3, "Defence", "bodkinhead_name"
    BODKINHEAD_L4 = 933, 4, "Defence", "bodkinhead_name"
    BODKINHEAD_L5 = 934, 5, "Defence", "bodkinhead_name"
    BODKINHEAD_L6 = 935, 6, "Defence", "bodkinhead_name"
    BODKINHEAD_L7 = 936, 7, "Defence", "bodkinhead_name"
    BODKINHEAD_L8 = 937, 8, "Defence", "bodkinhead_name"
    BODKINHEAD_L9 = 938, 9, "Defence", "bodkinhead_name"
    BODKINHEAD_L10 = 939, 10, "Defence", "bodkinhead_name"
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_LEFT_WEAK = 964, -1, "Attack", "arefungalswarmwalldelayincreaseleftweak_name"
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_FRONT_WEAK = 965, -1, "Attack", "arefungalswarmwalldelayincreasefrontweak_name"
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_RIGHT_WEAK = 966, -1, "Attack", "arefungalswarmwalldelayincreaserightweak_name"
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_ALL_WEAK = 967, -1, "Attack", "arefungalswarmwalldelayincreaseallweak_name"
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_LEFT_NORMAL = (
        968,
        -1,
        "Attack",
        "arefungalswarmwalldelayincreaseleftnormal_name",
    )
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_FRONT_NORMAL = (
        969,
        -1,
        "Attack",
        "arefungalswarmwalldelayincreasefrontnormal_name",
    )
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_RIGHT_NORMAL = (
        970,
        -1,
        "Attack",
        "arefungalswarmwalldelayincreaserightnormal_name",
    )
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_ALL_NORMAL = 971, -1, "Attack", "arefungalswarmwalldelayincreaseallnormal_name"
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_LEFT_STRONG = (
        972,
        -1,
        "Attack",
        "arefungalswarmwalldelayincreaseleftstrong_name",
    )
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_FRONT_STRONG = (
        973,
        -1,
        "Attack",
        "arefungalswarmwalldelayincreasefrontstrong_name",
    )
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_RIGHT_STRONG = (
        974,
        -1,
        "Attack",
        "arefungalswarmwalldelayincreaserightstrong_name",
    )
    ARE_FUNGAL_SWARM_WALL_DELAY_INCREASE_ALL_STRONG = 975, -1, "Attack", "arefungalswarmwalldelayincreaseallstrong_name"
    ARE_FUNGAL_SWARM_SPORE_KILLING_TOOL_MELEE_WEAK = 976, -1, "Attack", "arefungalswarmsporekillingtoolmeleeweak_name"
    ARE_FUNGAL_SWARM_SPORE_KILLING_TOOL_MELEE_MEDIUM = (
        977,
        -1,
        "Attack",
        "arefungalswarmsporekillingtoolmeleemedium_name",
    )
    ARE_FUNGAL_SWARM_SPORE_KILLING_TOOL_MELEE_STRONG = (
        978,
        -1,
        "Attack",
        "arefungalswarmsporekillingtoolmeleestrong_name",
    )
    ARE_FUNGAL_SWARM_SPORE_KILLING_TOOL_RANGED_WEAK = 979, -1, "Attack", "arefungalswarmsporekillingtoolrangedweak_name"
    ARE_FUNGAL_SWARM_SPORE_KILLING_TOOL_RANGED_MEDIUM = (
        980,
        -1,
        "Attack",
        "arefungalswarmsporekillingtoolrangedmedium_name",
    )
    ARE_FUNGAL_SWARM_SPORE_KILLING_TOOL_RANGED_STRONG = (
        981,
        -1,
        "Attack",
        "arefungalswarmsporekillingtoolrangedstrong_name",
    )
