"""Highscore list types."""

from enum import IntEnum


class RankingType(IntEnum):
    """
    A highscore list, the ``LT`` of ``hgh``, ``llsp``, ``llsw`` and ``slse``.

    The client's ``PLAYER_BUILDINGS`` (6) and ``ALLIANCE_BUILDINGS`` (11) are
    other names for ``PLAYER_MIGHT_POINTS`` and ``ALLIANCE_MIGHT_POINTS``.

    Client: ``HighscoreConst`` (dll line 19438)
    """

    PLAYER_ACHIEVEMENT_POINTS = 1
    PLAYER_WEEKLY_LOOT = 2
    PLAYER_HONOR = 5
    PLAYER_MIGHT_POINTS = 6
    PLAYER_LEGEND = 7
    ALLIANCE_HONOR = 10
    ALLIANCE_MIGHT_POINTS = 11
    ALLIANCE_LANDMARKS = 12
    ALLIANCE_AQUA_POINTS = 13
    TOURNAMENT_FAME = 20
    ALLIANCE_TOURNAMENT_FAME = 21
    FACTION_TOURNAMENT = 30
    POINT_EVENT = 40
    BEGGING_KNIGHTS = 41
    ALIEN_INVASION = 42
    LUCKY_WHEEL = 43
    ALLIANCE_ALIEN_INVASION_PLAYER = 44
    ALLIANCE_ALIEN_INVASION_ALLIANCE = 45
    ALLIANCE_NOMADINVASION_PLAYER = 46
    ALLIANCE_NOMADINVASION_ALLIANCE = 47
    NOMADINVASION = 48
    COLOSSUS = 50
    SAMURAI_PLAYER = 51
    SAMURAI_ALLIANCE = 52
    LONG_TERM_POINT_EVENT = 53
    FACTION_INVASION_PLAYER_BLUE = 54
    FACTION_INVASION_PLAYER_RED = 55
    FACTION_INVASION_ALLIANCE = 56
    ALLIANCE_RED_ALIEN_INVASION_PLAYER = 58
    ALLIANCE_RED_ALIEN_INVASION_ALLIANCE = 59
    TEMP_SERVER_DAILY_MIGHT_POINTS_BUILDINGS = 61
    TEMP_SERVER_GLOBAL = 62
    KINGDOMS_LEAGUE_SEASON = 63
    KINGDOMS_LEAGUE_SEASON_EVENT = 64
    TEMP_SERVER_DAILY_COLLECTOR_POINTS = 65
    TEMP_SERVER_DAILY_RANK_SWAP = 66
    ALLIANCE_KINGDOMS_LEAGUE_SEASON = 67
    ALLIANCE_KINGDOMS_LEAGUE_SEASON_EVENT = 68
    ALLIANCE_DAIMYO = 69
    ALLIANCE_BATTLE_GROUND_ALLIANCE_COLLECTOR = 70
    ALLIANCE_BATTLE_GROUND_PLAYER_COLLECTOR = 71
    LUCKY_WHEEL_SALE_DAYS = 72
    ALLIANCE_BATTLE_GROUND_ALLIANCE_TOWER = 74
    ALLIANCE_BATTLE_GROUND_PLAYER_TOWER = 75
    TEMPSERVER_PREVIOUS_RUN_PLAYER = 76
    ALLIANCE_BATTLE_GROUND_PREVIOUS_RUN_ALLIANCE = 77
    ALLIANCE_BATTLE_GROUND_PREVIOUS_RUN_PLAYER = 78
    DONATION_EVENT = 79
    DECO_GACHA_EVENT = 80
    CHRISTMAS_GACHA_EVENT = 81
    EASTER_GACHA_EVENT = 82
    SUMMER_GACHA_EVENT = 83
    ALLIANCE_MOBILISATION_EVENT = 84
    ANNIVERSARY_GACHA_EVENT = 85
    HALLOWEEN_GACHA_EVENT = 86
    BLACK_FRIDAY_GACHA_EVENT = 87
    CARNIVAL_GACHA_EVENT = 88
    ALLIANCE_RAID_MOBILISATION_EVENT = 89
    ALLIANCE_SAMURAI_ALIEN_INVASION_PLAYER = 500
    ALLIANCE_SAMURAI_ALIEN_INVASION_ALLIANCE = 501
